import type { DynastyDirectionResult, DynastyParticipant } from "../../lib/trade-analyzer/dynastyDirectionTypes";

export default function DynastyOutlookPanel({ result }: { result: DynastyDirectionResult | null | undefined }) {
  if (!result) return null;
  return <section className="lcc2-card lcc2-card--raised p-5 sm:p-6" aria-labelledby="dynasty-outlook-heading"><p className="lcc2-label">Dynasty Outlook</p><h2 id="dynasty-outlook-heading" className="mt-1 font-ui text-2xl font-black text-[var(--lcc-color-text)]">How this trade fits each franchise&apos;s current competitive window</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{result.participants.map((participant) => <OutlookCard key={participant.franchiseId} participant={participant} />)}</div><p className="mt-4 text-xs text-[var(--lcc-color-text-muted)]">Dynasty Outlook is separate from market value and roster impact. It does not declare a winner or make an accept/reject recommendation.</p></section>;
}

function OutlookCard({ participant }: { participant: DynastyParticipant }) { return <article className="rounded-lg border border-[var(--lcc-color-border)] p-4"><h3 className="font-ui text-lg font-black text-[var(--lcc-color-text)]">{participant.franchiseName}</h3><div className="mt-3 flex flex-wrap gap-2"><span className="lcc2-badge lcc2-badge--info">{participant.before.direction}</span><span className="lcc2-label">Confidence: {participant.before.confidence}</span></div><p className="mt-3 font-ui text-base font-black text-[var(--lcc-brand-primary)]">Trade Fit · {participant.tradeFit}</p><p className="lcc2-body mt-1">{fitExplanation(participant)}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Win-now" value={lineupText(participant)} /><Field label="Long-term" value={longTermText(participant)} /><Field label="Direction" value={participant.directionChanged ? `Direction changes to ${participant.after.direction}.` : `Direction remains ${participant.after.direction}.`} /><Field label="Evidence" value={participant.after.confidence} /></dl></article>; }
function lineupText(participant: DynastyParticipant) { return participant.changes.lineupStrength === "IMPROVED" ? "Starting lineup gets stronger." : participant.changes.lineupStrength === "REDUCED" ? "Starting lineup gets weaker." : participant.changes.lineupStrength === "UNCHANGED" ? "Starting lineup is unchanged." : "Starting-lineup evidence is unavailable."; }
function longTermText(participant: DynastyParticipant) { const changes = [participant.changes.age === "YOUNGER" ? "Roster becomes younger." : participant.changes.age === "OLDER" ? "Roster becomes older." : null, participant.changes.futureCapital === "INCREASED" ? "Future capital increases." : participant.changes.futureCapital === "DECREASED" ? "Future capital decreases." : null, participant.changes.rosterValue === "INCREASED" ? "Measured asset value increases." : participant.changes.rosterValue === "DECREASED" ? "Measured asset value decreases." : null].filter(Boolean); return changes.length ? changes.join(" ") : "No measured long-term change."; }
function fitExplanation(participant: DynastyParticipant) { return participant.fitReasons.join(" "); }
function Field({ label, value }: { label: string; value: string }) { return <div><dt className="lcc2-label">{label}</dt><dd className="mt-1 text-sm font-bold text-[var(--lcc-color-text)]">{value}</dd></div>; }
