import type { DynastyDirectionResult, DynastyParticipant } from "../../lib/trade-analyzer/dynastyDirectionTypes";

export default function DynastyOutlookPanel({ result }: { result: DynastyDirectionResult | null | undefined }) {
  if (!result) return null;
  return <section className="lcc2-card lcc2-card--raised p-5 sm:p-6" aria-labelledby="dynasty-outlook-heading"><p className="lcc2-label">Dynasty Outlook</p><h2 id="dynasty-outlook-heading" className="mt-1 font-ui text-2xl font-black text-[var(--lcc-color-text)]">How this trade fits each franchise&apos;s current competitive window</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{result.participants.map((participant) => <OutlookCard key={participant.franchiseId} participant={participant} />)}</div><p className="mt-4 text-xs text-[var(--lcc-color-text-muted)]">Dynasty Outlook is separate from market value and roster impact. It does not declare a winner or make an accept/reject recommendation.</p></section>;
}

function OutlookCard({ participant }: { participant: DynastyParticipant }) { const evidence = participant.presentation; if (!evidence) return <article className="rounded-lg border border-[var(--lcc-color-border)] p-4"><h3 className="font-ui text-lg font-black text-[var(--lcc-color-text)]">{participant.franchiseName}</h3><p className="lcc2-label mt-3">DYNASTY OUTLOOK UNAVAILABLE</p><p className="lcc2-body mt-1">Detailed dynasty evidence is unavailable for this franchise.</p><div className="mt-3 flex flex-wrap gap-2"><span className="lcc2-badge lcc2-badge--info">{participant.before.direction}</span><span className="lcc2-label">Confidence: {participant.before.confidence}</span><span className="lcc2-label">Trade Fit · {participant.tradeFit}</span></div></article>; return <article className="rounded-lg border border-[var(--lcc-color-border)] p-4"><h3 className="font-ui text-lg font-black text-[var(--lcc-color-text)]">{participant.franchiseName}</h3><div className="mt-3 flex flex-wrap gap-2"><span className="lcc2-badge lcc2-badge--info">{participant.before.direction}</span><span className="lcc2-label">Confidence: {participant.before.confidence}</span></div><p className="mt-3 font-ui text-base font-black text-[var(--lcc-brand-primary)]">Trade Fit · {participant.tradeFit}</p><p className="lcc2-body mt-1">{evidence.fitExplanation}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Win-now" value={evidence.winNow} /><Field label="Career Window" value={`${evidence.careerWindow.label}. ${evidence.careerWindow.detail}`} /><Field label="Future Capital" value={`${evidence.futureCapital.label}. ${evidence.futureCapital.detail}`} /><Field label="Asset Profile" value={evidence.assetProfile.detail} /><Field label="Direction" value={evidence.direction} /></dl></article>; }
function Field({ label, value }: { label: string; value: string }) { return <div><dt className="lcc2-label">{label}</dt><dd className="mt-1 text-sm font-bold text-[var(--lcc-color-text)]">{value}</dd></div>; }
