"use client";

import { useMemo, useState } from "react";

export interface TradeAnalyzerCatalogAsset {
  assetId: string;
  displayName: string;
  assetType: "PLAYER" | "PICK" | "K" | "DST" | "UNSUPPORTED";
  position?: string;
  season?: number;
  round?: number;
  slot?: number;
  pickKind?: string;
  ownerName?: string;
  marketValue?: number;
  valueStatus: string;
  evidence?: string;
}

type Result = { ok: true; data: ApiData } | { ok: false; error?: { message?: string } };
type ApiData = { engineStatus: string | null; snapshot: { snapshotDate: string } | null; sideA: SideResult | null; sideB: SideResult | null; trade: TradeResult | null; warnings: string[] };
type SideResult = { assets: Array<{ assetId: string; displayName: string; baseValue?: number; valueStatus: string; evidence?: string }>; rawValue: number; marketShare: { display: number } | null; evidence: string };
type TradeResult = { fairnessScore: { display: number } | null; fairnessBand: string | null; marketEdgeSide: string | null; evidence: string; resultStatus: string };

const positions = ["ALL", "QB", "RB", "WR", "TE", "K", "DST"];
const money = (value: number) => value >= 1000 ? `${(value / 1000).toFixed(1)}K` : Math.round(value).toLocaleString();
const errorMessage = (status: number) => ({ 400: "One or more selected assets are unavailable.", 401: "Sign-in required.", 403: "Trade Analyzer is not available yet.", 413: "That request is too large.", 415: "Trade Analyzer requires JSON input.", 429: "Too many requests — try again shortly.", 500: "Unable to analyze this trade right now.", 503: "Trade Analyzer is temporarily unavailable." }[status] ?? "Unable to analyze this trade right now.");

export default function TradeAnalyzerClient({ catalog, snapshotDate }: { catalog: TradeAnalyzerCatalogAsset[]; snapshotDate: string }) {
  const [sideA, setSideA] = useState<string[]>([]), [sideB, setSideB] = useState<string[]>([]);
  const [query, setQuery] = useState(""), [position, setPosition] = useState("ALL"), [group, setGroup] = useState<"PLAYERS" | "PICKS">("PLAYERS");
  const [result, setResult] = useState<ApiData | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  const selected = useMemo(() => new Set([...sideA, ...sideB]), [sideA, sideB]);
  const visible = useMemo(() => catalog.filter((asset) => (group === "PICKS" ? asset.assetType === "PICK" : asset.assetType !== "PICK") && (!query.trim() || `${asset.displayName} ${asset.ownerName ?? ""}`.toLowerCase().includes(query.trim().toLowerCase())) && (group === "PICKS" || position === "ALL" || asset.position === position)).slice(0, 80), [catalog, group, position, query]);
  const add = (id: string, side: "A" | "B") => { if (selected.has(id)) return; const setter = side === "A" ? setSideA : setSideB; setter((items) => items.length < 15 ? [...items, id] : items); setResult(null); };
  const remove = (id: string) => { setSideA((items) => items.filter((item) => item !== id)); setSideB((items) => items.filter((item) => item !== id)); setResult(null); };
  const analyze = async () => { if (!sideA.length || !sideB.length || loading) return; setLoading(true); setError(""); setResult(null); try { const response = await fetch("/api/trade-analyzer/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sideA: { assetIds: sideA }, sideB: { assetIds: sideB } }) }); const payload = await response.json() as Result; if (!response.ok || !payload.ok) setError(payload.ok ? "Unable to analyze this trade right now." : payload.error?.message ?? errorMessage(response.status)); else setResult(payload.data); } catch { setError("Unable to analyze this trade right now."); } finally { setLoading(false); } };
  const reset = () => { setSideA([]); setSideB([]); setResult(null); setError(""); };
  const swap = () => { setSideA(sideB); setSideB(sideA); setResult(null); };
  const assets = (ids: string[]) => ids.map((id) => catalog.find((asset) => asset.assetId === id)).filter(Boolean) as TradeAnalyzerCatalogAsset[];
  return <main className="lcc2-page-shell"><div className="lcc2-page-container">
    <header className="max-w-3xl"><p className="lcc2-label text-[var(--lcc-brand-primary)]">Private Dynasty Operations</p><h1 className="mt-2 font-ui text-4xl font-black tracking-[-0.04em] text-[var(--lcc-color-text)] sm:text-5xl">Trade Analyzer</h1><p className="lcc2-body mt-3">Explore a hypothetical trade using the approved current market snapshot. The analyzer describes market fairness; it does not recommend, submit, or save a trade.</p></header>
    <section className="mt-8 grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]" aria-label="Trade sides"><SideCard label="SIDE A" items={assets(sideA)} remove={remove} /><SideCard label="SIDE B" items={assets(sideB)} remove={remove} /></section>
    <section className="lcc2-card mt-5 p-4 sm:p-5" aria-labelledby="asset-picker-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="lcc2-label">Asset picker</p><h2 id="asset-picker-heading" className="mt-1 font-ui text-2xl font-black text-[var(--lcc-color-text)]">Build both sides</h2></div><p className="lcc2-body text-sm">{sideA.length}/15 + {sideB.length}/15 selected</p></div><div className="mt-4 grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto_auto]"><label className="grid gap-1"><span className="lcc2-label">Search players and picks</span><input aria-label="Search players and picks" value={query} onChange={(event) => setQuery(event.target.value)} className="lcc2-input" placeholder="Search by name or team" /></label><label className="grid gap-1"><span className="lcc2-label">Group</span><select aria-label="Asset group" value={group} onChange={(event) => setGroup(event.target.value as "PLAYERS" | "PICKS")} className="lcc2-input"><option value="PLAYERS">Players</option><option value="PICKS">Picks</option></select></label>{group === "PLAYERS" ? <label className="grid gap-1"><span className="lcc2-label">Position</span><select aria-label="Player position" value={position} onChange={(event) => setPosition(event.target.value)} className="lcc2-input">{positions.map((item) => <option key={item}>{item}</option>)}</select></label> : <div />}</div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{visible.map((asset) => <AssetRow key={asset.assetId} asset={asset} selected={selected.has(asset.assetId)} add={add} />)}</div>{visible.length === 80 ? <p className="lcc2-body mt-3 text-sm">Showing the first 80 matches. Refine your search to find a specific asset.</p> : null}</section>
    <div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={analyze} disabled={!sideA.length || !sideB.length || loading} className="lcc2-button lcc2-button--primary disabled:cursor-not-allowed disabled:opacity-50">{loading ? "Analyzing…" : "Analyze Trade"}</button><button type="button" onClick={swap} disabled={!sideA.length && !sideB.length} className="lcc2-button lcc2-button--secondary disabled:cursor-not-allowed disabled:opacity-50">Swap Sides</button><button type="button" onClick={reset} className="lcc2-button lcc2-button--secondary">Reset Trade</button></div>
    <div className="mt-5" aria-live="polite">{error ? <div className="lcc2-card border-[var(--lcc-color-warning)] p-4"><p className="font-ui font-black text-[var(--lcc-color-text)]">{error}</p></div> : null}{result ? <ResultView result={result} catalog={catalog} snapshotDate={snapshotDate} /> : null}</div>
  </div></main>;
}

function SideCard({ label, items, remove }: { label: string; items: TradeAnalyzerCatalogAsset[]; remove: (id: string) => void }) { return <article className="lcc2-card lcc2-card--raised p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-ui text-xl font-black text-[var(--lcc-color-text)]">{label}</h2><span className="lcc2-label">{items.length}/15 assets</span></div>{items.length ? <ul className="mt-4 space-y-2">{items.map((asset) => <li key={asset.assetId} className="flex items-start justify-between gap-3 rounded-lg border border-[var(--lcc-color-border)] p-3"><div className="min-w-0"><p className="font-ui font-black text-[var(--lcc-color-text)]">{asset.displayName}</p><p className="lcc2-body text-sm">{asset.position ?? "Pick"}{asset.ownerName ? ` · ${asset.ownerName}` : ""}{asset.marketValue !== undefined ? ` · ${money(asset.marketValue)}` : ""}</p></div><button type="button" onClick={() => remove(asset.assetId)} aria-label={`Remove ${asset.displayName} from ${label}`} className="lcc2-button lcc2-button--secondary shrink-0 px-3 py-2 text-sm">Remove</button></li>)}</ul> : <p className="lcc2-body mt-4">Select one or more assets below.</p>}</article>; }
function AssetRow({ asset, selected, add }: { asset: TradeAnalyzerCatalogAsset; selected: boolean; add: (id: string, side: "A" | "B") => void }) { return <div className="rounded-lg border border-[var(--lcc-color-border)] bg-[var(--lcc-color-surface)] p-3"><div className="min-w-0"><p className="truncate font-ui font-black text-[var(--lcc-color-text)]">{asset.displayName}</p><p className="lcc2-body text-sm">{asset.assetType === "PICK" ? "Draft pick" : asset.position ?? asset.assetType}{asset.ownerName ? ` · ${asset.ownerName}` : ""}</p></div><div className="mt-3 flex flex-wrap gap-2">{asset.marketValue !== undefined ? <span className="lcc2-badge lcc2-badge--info">{money(asset.marketValue)}</span> : null}<button type="button" disabled={selected} onClick={() => add(asset.assetId, "A")} className="lcc2-button lcc2-button--secondary px-3 py-2 text-sm disabled:opacity-50">{selected ? "Selected" : "Add to Side A"}</button><button type="button" disabled={selected} onClick={() => add(asset.assetId, "B")} className="lcc2-button lcc2-button--secondary px-3 py-2 text-sm disabled:opacity-50">{selected ? "Selected" : "Add to Side B"}</button></div></div>; }
function ResultView({ result, catalog, snapshotDate }: { result: ApiData; catalog: TradeAnalyzerCatalogAsset[]; snapshotDate: string }) { if (!result.trade || !result.sideA || !result.sideB || result.trade.resultStatus === "SUPPRESSED") return <section className="lcc2-card mt-5 p-5" aria-label="Trade result"><p className="lcc2-label">Fairness unavailable</p><h2 className="mt-2 font-ui text-2xl font-black text-[var(--lcc-color-text)]">Value unavailable for one or more assets.</h2><p className="lcc2-body mt-2">Selected assets are shown above; this trade does not receive a fabricated fairness score.</p></section>; const side = (item: SideResult) => <div className="lcc2-card p-4"><p className="lcc2-label">{item === result.sideA ? "Side A" : "Side B"}</p><p className="mt-2 font-ui text-2xl font-black text-[var(--lcc-color-text)]">{money(item.rawValue)}</p><p className="lcc2-body mt-1">{item.marketShare ? `${item.marketShare.display.toFixed(1)}% market share` : "Market share unavailable"}</p><p className="lcc2-body mt-1">Evidence · {item.evidence}</p><ul className="mt-3 space-y-1">{item.assets.map((asset) => <li key={asset.assetId} className="lcc2-body text-sm">{catalog.find((candidate) => candidate.assetId === asset.assetId)?.displayName ?? asset.displayName}{asset.baseValue !== undefined ? ` · ${money(asset.baseValue)}` : ""}</li>)}</ul></div>; return <section className="mt-5" aria-label="Authoritative trade result"><div className="lcc2-card lcc2-card--raised p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="lcc2-label">{result.trade.resultStatus === "PROVISIONAL" ? "Provisional" : "Authoritative"} result</p><h2 className="mt-2 font-ui text-4xl font-black text-[var(--lcc-color-text)]">{result.trade.fairnessScore ? `${result.trade.fairnessScore.display.toFixed(1)} / 100` : "Fairness unavailable"}</h2><p className="lcc2-body mt-1">{result.trade.fairnessBand ?? "Value unavailable for one or more assets."}</p></div><div className="text-left sm:text-right"><p className="lcc2-label">Market edge</p><p className="font-ui text-xl font-black text-[var(--lcc-color-text)]">{result.trade.marketEdgeSide === "NONE" ? "Even" : result.trade.marketEdgeSide === "SIDE_A" ? "Side A" : "Side B"}</p><p className="lcc2-body text-sm">Evidence · {result.trade.evidence}</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2">{side(result.sideA)}{side(result.sideB)}</div><p className="lcc2-body mt-4 text-sm">Snapshot: {new Date(snapshotDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" })}</p></div></section>; }
