export const LCC_ERA_MODEL = {
  twoKeeper: {
    label: "Two-Keeper Era",
    startSeason: 2003,
    endSeason: 2020,
  },
  sleeperMigration: {
    label: "Sleeper migration",
    season: 2019,
  },
  dynasty: {
    label: "Dynasty Era",
    startSeason: 2021,
  },
} as const;

export type LccOwnerStatus = "active" | "retired";
export type LccOwnerDivision = "OG" | "NEWBIE";
export type LccOwnerEraKey = keyof typeof LCC_ERA_MODEL;

export interface LccOwnerPodiums {
  readonly first: readonly string[];
  readonly second: readonly string[];
  readonly third: readonly string[];
}

export interface LccOwnerProfile {
  readonly bio?: string;
  readonly location?: string;
  readonly favoriteNflTeam?: string;
  readonly almanacNotes?: string;
  readonly publicPageEnabled?: boolean;
  readonly profileSlug?: string;
}

export interface LccOwnerManagerCard {
  readonly sleeperName: string;
  readonly division?: LccOwnerDivision;
  readonly badgeLabel: string;
  readonly nflTeam: string;
  readonly rivalNickname?: string;
  readonly rivalAvatarFilename?: string;
  readonly phone?: string;
  readonly tradeAggression?: number;
  readonly titles: number;
  readonly podiums: LccOwnerPodiums;
}

export interface LccOwner {
  readonly id: string;
  readonly status: LccOwnerStatus;
  readonly sleeperUserId?: string;
  readonly displayName: string;
  readonly nickname: string;
  readonly avatarFilename: string;
  readonly aliases: readonly string[];
  readonly displayNameHistory: readonly string[];
  readonly founder: boolean;
  readonly commissioner: boolean;
  readonly original2003Owner: boolean;
  readonly inMemoriam: boolean;
  readonly joinedYear?: number;
  readonly eraTags: readonly LccOwnerEraKey[];
  readonly managerPage: LccOwnerManagerCard;
  readonly profile?: LccOwnerProfile;
}

const emptyPodiums: LccOwnerPodiums = {
  first: [],
  second: [],
  third: [],
};

export const ACTIVE_LCC_OWNERS: readonly LccOwner[] = [
  {
    id: "ray-long",
    status: "active",
    sleeperUserId: "342828350391230464",
    displayName: "Ray Long",
    nickname: "Ray",
    avatarFilename: "Ray.png",
    aliases: ["Ray", "Ray Long", "Bower Rangers"],
    displayNameHistory: ["Bower Rangers"],
    founder: true,
    commissioner: true,
    original2003Owner: true,
    inMemoriam: false,
    joinedYear: 2003,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "Bower Rangers",
      division: "OG",
      badgeLabel: "FOUNDER",
      nflTeam: "atl",
      rivalNickname: "Jeffrey",
      rivalAvatarFilename: "Jeffrey.png",
      phone: "8046471100",
      tradeAggression: 10,
      titles: 1,
      podiums: {
        first: ["2007"],
        second: ["2005", "2008", "2014"],
        third: ["2009", "2021"],
      },
    },
    profile: {
      profileSlug: "ray-long",
      publicPageEnabled: false,
    },
  },
  {
    id: "bill-gross",
    status: "active",
    sleeperUserId: "466780021365665792",
    displayName: "Bill Gross",
    nickname: "Bill",
    avatarFilename: "Bill.png",
    aliases: ["Bill", "Bill Gross", "Chicago Cutlers"],
    displayNameHistory: ["Chicago Cutlers"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: false,
    joinedYear: 2003,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "Chicago Cutlers",
      division: "OG",
      badgeLabel: "FOUNDER",
      nflTeam: "chi",
      rivalNickname: "Ray",
      rivalAvatarFilename: "Ray.png",
      phone: "8043077897",
      tradeAggression: 3,
      titles: 4,
      podiums: {
        first: ["2003", "2005", "2006", "2018"],
        second: ["2016", "2024"],
        third: ["2013"],
      },
    },
    profile: {
      profileSlug: "bill-gross",
      publicPageEnabled: false,
    },
  },
  {
    id: "keith-winder",
    status: "active",
    sleeperUserId: "466638004102885376",
    displayName: "Keith Winder",
    nickname: "KW",
    avatarFilename: "KW.png",
    aliases: ["KW", "Keith Winder", "Off Constantly"],
    displayNameHistory: ["Off Constantly"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: false,
    joinedYear: 2003,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "Off Constantly",
      division: "OG",
      badgeLabel: "FOUNDER",
      nflTeam: "was",
      rivalNickname: "Bill",
      rivalAvatarFilename: "Bill.png",
      phone: "8048526684",
      tradeAggression: 3,
      titles: 1,
      podiums: {
        first: ["2020"],
        second: ["2004", "2017"],
        third: ["2015", "2023"],
      },
    },
    profile: {
      profileSlug: "keith-winder",
      publicPageEnabled: false,
    },
  },
  {
    id: "rob-jenkins",
    status: "active",
    sleeperUserId: "467786127214899200",
    displayName: "Rob Jenkins",
    nickname: "Rob",
    avatarFilename: "Rob.png",
    aliases: ["Rob", "Rob Jenkins", "iamaloser", "Roaring20", "Roaring 20"],
    displayNameHistory: ["iamaloser", "Roaring20", "Roaring 20"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2004,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "Roaring 20",
      division: "OG",
      badgeLabel: "OG",
      nflTeam: "det",
      rivalNickname: "Ray",
      rivalAvatarFilename: "Ray.png",
      phone: "8044008140",
      tradeAggression: 9,
      titles: 2,
      podiums: {
        first: ["2014"],
        second: ["2005", "2009", "2017", "2021"],
        third: ["2015", "2016", "2020"],
      },
    },
    profile: {
      profileSlug: "rob-jenkins",
      publicPageEnabled: false,
    },
  },
  {
    id: "earl-perkins",
    status: "active",
    sleeperUserId: "466645286870052864",
    displayName: "Earl Perkins",
    nickname: "EP",
    avatarFilename: "EP.png",
    aliases: ["EP", "Earl", "Earl Perkins", "The People's Team"],
    displayNameHistory: ["The People's Team"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2004,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "The People's Team",
      division: "OG",
      badgeLabel: "OG",
      nflTeam: "phi",
      rivalNickname: "Bill",
      rivalAvatarFilename: "Bill.png",
      phone: "447825990288",
      tradeAggression: 9,
      titles: 1,
      podiums: {
        first: ["2022"],
        second: ["2020"],
        third: ["2006", "2008", "2018", "2023"],
      },
    },
    profile: {
      profileSlug: "earl-perkins",
      publicPageEnabled: false,
    },
  },
  {
    id: "jeffrey-hudgins",
    status: "active",
    sleeperUserId: "356621920969555968",
    displayName: "Jeffrey Hudgins",
    nickname: "Jeffrey",
    avatarFilename: "Jeffrey.png",
    aliases: ["Jeffrey", "Jeffrey Hudgins", "CeeDees....Cousins"],
    displayNameHistory: ["CeeDees....Cousins"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2007,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "CeeDees....Cousins",
      division: "OG",
      badgeLabel: "OG",
      nflTeam: "atl",
      rivalNickname: "Ray",
      rivalAvatarFilename: "Ray.png",
      phone: "4049318499",
      tradeAggression: 6,
      titles: 1,
      podiums: {
        first: ["2024"],
        second: ["2013", "2019"],
        third: ["2023"],
      },
    },
    profile: {
      profileSlug: "jeffrey-hudgins",
      publicPageEnabled: false,
    },
  },
  {
    id: "tyrone-poist",
    status: "active",
    sleeperUserId: "466797853767888896",
    displayName: "Tyrone Poist",
    nickname: "Tyrone",
    avatarFilename: "Tyrone.png",
    aliases: ["Tyrone", "Tyrone Poist", "Won't You be my Nabers"],
    displayNameHistory: ["Won't You be my Nabers"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2004,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "Won't You be my Nabers",
      division: "NEWBIE",
      badgeLabel: "CHAMP",
      nflTeam: "nyg",
      rivalNickname: "Ben",
      rivalAvatarFilename: "Ben.png",
      phone: "7577617610",
      tradeAggression: 5,
      titles: 2,
      podiums: {
        first: ["2015", "2025"],
        second: ["2016"],
        third: ["2004"],
      },
    },
    profile: {
      profileSlug: "tyrone-poist",
      publicPageEnabled: false,
    },
  },
  {
    id: "ben-isbell",
    status: "active",
    sleeperUserId: "346727603970973696",
    displayName: "Ben Isbell",
    nickname: "Ben",
    avatarFilename: "Ben.png",
    aliases: ["Ben", "Ben Isbell", "Benl"],
    displayNameHistory: ["Benl"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2008,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "Benl",
      division: "NEWBIE",
      badgeLabel: "VET",
      nflTeam: "dal",
      rivalNickname: "Tyrone",
      rivalAvatarFilename: "Tyrone.png",
      phone: "8043146253",
      tradeAggression: 3,
      titles: 2,
      podiums: {
        first: ["2011", "2016"],
        second: ["2015", "2022", "2023", "2024"],
        third: ["2025"],
      },
    },
    profile: {
      profileSlug: "ben-isbell",
      publicPageEnabled: false,
    },
  },
  {
    id: "loren-michaels",
    status: "active",
    sleeperUserId: "466645950710935552",
    displayName: "Loren Michaels",
    nickname: "Loren",
    avatarFilename: "Loren.png",
    aliases: ["Loren", "Loren Michaels", "ICOR 4 Lyfe"],
    displayNameHistory: ["ICOR 4 Lyfe"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2011,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "ICOR 4 Lyfe",
      division: "NEWBIE",
      badgeLabel: "VET",
      nflTeam: "atl",
      rivalNickname: "Ben",
      rivalAvatarFilename: "Ben.png",
      phone: "8285459802",
      tradeAggression: 8,
      titles: 1,
      podiums: {
        first: ["2021"],
        second: ["2011", "2023"],
        third: ["2012", "2024"],
      },
    },
    profile: {
      profileSlug: "loren-michaels",
      publicPageEnabled: false,
    },
  },
  {
    id: "mike-mcburnie",
    status: "active",
    sleeperUserId: "466659300316540928",
    displayName: "Mike McBurnie",
    nickname: "Mike M",
    avatarFilename: "Mike M.png",
    aliases: ["Mike M", "Mike McBurnie", "CookieMonsters"],
    displayNameHistory: ["CookieMonsters"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2018,
    eraTags: ["twoKeeper", "sleeperMigration", "dynasty"],
    managerPage: {
      sleeperName: "CookieMonsters",
      division: "NEWBIE",
      badgeLabel: "VET",
      nflTeam: "phi",
      rivalNickname: "Ray",
      rivalAvatarFilename: "Ray.png",
      phone: "8042399371",
      tradeAggression: 5,
      titles: 1,
      podiums: {
        first: ["2019", "2023"],
        second: ["2020", "2025"],
        third: [],
      },
    },
    profile: {
      profileSlug: "mike-mcburnie",
      publicPageEnabled: false,
    },
  },
  {
    id: "anthony-martinez",
    status: "active",
    sleeperUserId: "468192726756618240",
    displayName: "Anthony Martinez",
    nickname: "Amart",
    avatarFilename: "Amart.png",
    aliases: ["Amart", "Anthony Martinez", "Sycamore Bishops"],
    displayNameHistory: ["Sycamore Bishops"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2020,
    eraTags: ["twoKeeper", "dynasty"],
    managerPage: {
      sleeperName: "Sycamore Bishops",
      division: "NEWBIE",
      badgeLabel: "ACTIVE",
      nflTeam: "pit",
      rivalNickname: "Mike E",
      rivalAvatarFilename: "Mike E.png",
      phone: "8048524252",
      tradeAggression: 8,
      titles: 0,
      podiums: {
        first: [],
        second: [],
        third: ["2021"],
      },
    },
    profile: {
      profileSlug: "anthony-martinez",
      publicPageEnabled: false,
    },
  },
  {
    id: "mike-estes",
    status: "active",
    sleeperUserId: "817056809218080768",
    displayName: "Mike Estes",
    nickname: "Mike E",
    avatarFilename: "Mike E.png",
    aliases: ["Mike E", "Mike Estes", "Redneck Rebels"],
    displayNameHistory: ["Redneck Rebels"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2022,
    eraTags: ["dynasty"],
    managerPage: {
      sleeperName: "Redneck Rebels",
      division: "NEWBIE",
      badgeLabel: "ACTIVE",
      nflTeam: "was",
      rivalNickname: "Amart",
      rivalAvatarFilename: "Amart.png",
      phone: "8044024955",
      tradeAggression: 9,
      titles: 0,
      podiums: {
        first: [],
        second: [],
        third: ["2025"],
      },
    },
    profile: {
      profileSlug: "mike-estes",
      publicPageEnabled: false,
    },
  },
];

export const RETIRED_LCC_OWNERS: readonly LccOwner[] = [
  {
    id: "dan-lowery",
    status: "retired",
    sleeperUserId: "466639810480566272",
    displayName: "Dan Lowery",
    nickname: "Dan",
    avatarFilename: "Dan.png",
    aliases: ["Dan", "Dan Lowery", "Ridiculousville Quicksand"],
    displayNameHistory: ["Ridiculousville Quicksand"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2006,
    eraTags: ["twoKeeper", "sleeperMigration"],
    managerPage: {
      sleeperName: "Ridiculousville Quicksand",
      badgeLabel: "RETIRED",
      nflTeam: "atl",
      titles: 3,
      podiums: {
        first: ["2012", "2013", "2017"],
        second: [],
        third: [],
      },
    },
    profile: {
      profileSlug: "dan-lowery",
      publicPageEnabled: false,
    },
  },
  {
    id: "chris-hofstede",
    status: "retired",
    displayName: "Chris Hofstede",
    nickname: "Chris H",
    avatarFilename: "Chris H.png",
    aliases: ["Chris H", "Chris Hofstede", "Boss Hogg is Back Baby!"],
    displayNameHistory: ["Boss Hogg is Back Baby!"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2005,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "Boss Hogg is Back Baby!",
      badgeLabel: "RETIRED",
      nflTeam: "was",
      titles: 1,
      podiums: {
        first: ["2008"],
        second: ["2006", "2007"],
        third: ["2005"],
      },
    },
    profile: {
      profileSlug: "chris-hofstede",
      publicPageEnabled: false,
    },
  },
  {
    id: "dj-king",
    status: "retired",
    displayName: "DJ King",
    nickname: "DJ",
    avatarFilename: "DJ.png",
    aliases: ["DJ", "DJ King", "H.S. Serial Killers"],
    displayNameHistory: ["H.S. Serial Killers"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2006,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "H.S. Serial Killers",
      badgeLabel: "RETIRED",
      nflTeam: "was",
      titles: 1,
      podiums: {
        first: ["2010"],
        second: [],
        third: [],
      },
    },
    profile: {
      profileSlug: "dj-king",
      publicPageEnabled: false,
    },
  },
  {
    id: "jd-wylie",
    status: "retired",
    displayName: "JD Wylie",
    nickname: "JD",
    avatarFilename: "JD.png",
    aliases: ["JD", "JD Wylie"],
    displayNameHistory: ["JD"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: false,
    joinedYear: 2003,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "JD",
      badgeLabel: "FOUNDER",
      nflTeam: "mia",
      titles: 0,
      podiums: {
        first: [],
        second: ["2013"],
        third: ["2007"],
      },
    },
    profile: {
      profileSlug: "jd-wylie",
      publicPageEnabled: false,
    },
  },
  {
    id: "david-gross",
    status: "retired",
    displayName: "David Gross",
    nickname: "David G",
    avatarFilename: "David G.png",
    aliases: ["David G", "David Gross", "British Bulldogs"],
    displayNameHistory: ["British Bulldogs"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2006,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "British Bulldogs",
      badgeLabel: "RETIRED",
      nflTeam: "chi",
      titles: 0,
      podiums: {
        first: [],
        second: [],
        third: ["2008"],
      },
    },
    profile: {
      profileSlug: "david-gross",
      publicPageEnabled: false,
    },
  },
  {
    id: "matt-hinkle",
    status: "retired",
    sleeperUserId: "466772731602399232",
    displayName: "Matt Hinkle",
    nickname: "Matt",
    avatarFilename: "Matt.png",
    aliases: ["Matt", "Matt H", "Matt Hinkle", "Bungholio79"],
    displayNameHistory: ["Bungholio79", "Matt H"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2008,
    eraTags: ["twoKeeper", "sleeperMigration"],
    managerPage: {
      sleeperName: "Matt H",
      badgeLabel: "RETIRED",
      nflTeam: "was",
      titles: 0,
      podiums: {
        first: [],
        second: ["2012", "2020"],
        third: ["2010", "2011", "2014"],
      },
    },
    profile: {
      profileSlug: "matt-hinkle",
      publicPageEnabled: false,
    },
  },
  {
    id: "david-beasley",
    status: "retired",
    displayName: "David Beasley",
    nickname: "David B",
    avatarFilename: "David B.png",
    aliases: ["David B", "David Beasley", "CAM You Dig It?!"],
    displayNameHistory: ["CAM You Dig It?!"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2006,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "CAM You Dig It?!",
      badgeLabel: "RETIRED",
      nflTeam: "car",
      titles: 0,
      podiums: {
        first: [],
        second: [],
        third: ["2013"],
      },
    },
    profile: {
      profileSlug: "david-beasley",
      publicPageEnabled: false,
    },
  },
  {
    id: "keith-douglas",
    status: "retired",
    displayName: "Keith Douglas",
    nickname: "KD",
    avatarFilename: "KD.png",
    aliases: ["KD", "Keith Douglas"],
    displayNameHistory: ["KD"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: false,
    joinedYear: 2003,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "KD",
      badgeLabel: "FOUNDER",
      nflTeam: "buf",
      titles: 0,
      podiums: {
        first: [],
        second: ["2005"],
        third: ["2003", "2004", "2006"],
      },
    },
    profile: {
      profileSlug: "keith-douglas",
      publicPageEnabled: false,
    },
  },
  {
    id: "bernie-stewart",
    status: "retired",
    displayName: "Bernie Stewart",
    nickname: "Bernie",
    avatarFilename: "Bernie.png",
    aliases: ["Bernie", "Bernie Stewart"],
    displayNameHistory: ["Bernie"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: false,
    joinedYear: 2003,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "Bernie",
      badgeLabel: "FOUNDER",
      nflTeam: "was",
      titles: 0,
      podiums: {
        first: [],
        second: [],
        third: ["2003"],
      },
    },
    profile: {
      profileSlug: "bernie-stewart",
      publicPageEnabled: false,
    },
  },
  {
    id: "bj",
    status: "retired",
    displayName: "BJ",
    nickname: "BJ",
    avatarFilename: "BJ.png",
    aliases: ["BJ"],
    displayNameHistory: ["BJ"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: false,
    joinedYear: 2003,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "BJ",
      badgeLabel: "FOUNDER",
      nflTeam: "was",
      titles: 0,
      podiums: emptyPodiums,
    },
    profile: {
      profileSlug: "bj",
      publicPageEnabled: false,
    },
  },
  {
    id: "chris-boschen",
    status: "retired",
    displayName: "Chris Boschen",
    nickname: "Chris B",
    avatarFilename: "Chris B.png",
    aliases: ["Chris B", "Chris Boschen"],
    displayNameHistory: ["Chris B"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: true,
    joinedYear: 2003,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "Chris B",
      badgeLabel: "MEMORIAL",
      nflTeam: "mia",
      titles: 0,
      podiums: {
        first: [],
        second: ["2012"],
        third: [],
      },
    },
    profile: {
      profileSlug: "chris-boschen",
      publicPageEnabled: false,
    },
  },
  {
    id: "junior",
    status: "retired",
    displayName: "Junior",
    nickname: "Junior",
    avatarFilename: "Junior.png",
    aliases: ["Junior"],
    displayNameHistory: ["Junior"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: true,
    joinedYear: 2003,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "Junior",
      badgeLabel: "MEMORIAL",
      nflTeam: "was",
      titles: 0,
      podiums: emptyPodiums,
    },
    profile: {
      profileSlug: "junior",
      publicPageEnabled: false,
    },
  },
  {
    id: "chris-morgan",
    status: "retired",
    displayName: "Chris Morgan",
    nickname: "Chris M",
    avatarFilename: "Chris M.png",
    aliases: ["Chris M", "Chris Morgan"],
    displayNameHistory: ["Chris M"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2005,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "Chris M",
      badgeLabel: "RETIRED",
      nflTeam: "dal",
      titles: 0,
      podiums: emptyPodiums,
    },
    profile: {
      profileSlug: "chris-morgan",
      publicPageEnabled: false,
    },
  },
  {
    id: "jay",
    status: "retired",
    displayName: "Jay",
    nickname: "Jay",
    avatarFilename: "Jay.png",
    aliases: ["Jay", "Vitamin J"],
    displayNameHistory: ["Vitamin J"],
    founder: false,
    commissioner: false,
    original2003Owner: true,
    inMemoriam: false,
    joinedYear: 2003,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "Vitamin J",
      badgeLabel: "FOUNDER",
      nflTeam: "mia",
      titles: 0,
      podiums: emptyPodiums,
    },
    profile: {
      profileSlug: "jay",
      publicPageEnabled: false,
    },
  },
  {
    id: "tommy-eckert",
    status: "retired",
    displayName: "Tommy Eckert",
    nickname: "Tommy",
    avatarFilename: "Tommy.png",
    aliases: ["Tommy", "Tommy Eckert"],
    displayNameHistory: ["Tommy"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2008,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "Tommy",
      badgeLabel: "RETIRED",
      nflTeam: "dal",
      titles: 0,
      podiums: emptyPodiums,
    },
    profile: {
      profileSlug: "tommy-eckert",
      publicPageEnabled: false,
    },
  },
  {
    id: "mike-lastfogel",
    status: "retired",
    displayName: "Mike Lastfogel",
    nickname: "Mike L",
    avatarFilename: "Mike L.png",
    aliases: ["Mike L", "Mike Lastfogel"],
    displayNameHistory: ["Mike L"],
    founder: false,
    commissioner: false,
    original2003Owner: false,
    inMemoriam: false,
    joinedYear: 2008,
    eraTags: ["twoKeeper"],
    managerPage: {
      sleeperName: "Mike L",
      badgeLabel: "RETIRED",
      nflTeam: "nyg",
      titles: 0,
      podiums: emptyPodiums,
    },
    profile: {
      profileSlug: "mike-lastfogel",
      publicPageEnabled: false,
    },
  },
];

export const ALL_LCC_OWNERS: readonly LccOwner[] = [
  ...ACTIVE_LCC_OWNERS,
  ...RETIRED_LCC_OWNERS,
];

export function getLccOwnerById(id: string): LccOwner | undefined {
  return ALL_LCC_OWNERS.find((owner) => owner.id === id);
}

export function getLccOwnerBySleeperUserId(
  sleeperUserId: string
): LccOwner | undefined {
  return ALL_LCC_OWNERS.find(
    (owner) => owner.sleeperUserId === sleeperUserId
  );
}
