// lib/managersData.ts

import { DEFAULT_OWNER_IMAGE, getOwnerImagePath } from "./ownerImages";

export interface Manager {
  roster: number;
  name: string;
  teamName?: string;
  coOwner?: string;
  tookOver?: number | null;
  location?: string;
  bio: string;
  photo: string;
  fantasyStart?: number;
  favoriteTeam: string;
  mode: "Win Now" | "Dynasty" | "Rebuild" | "Auctioneer" | "Retired" | string;
  rival: {
    name: string;
    link?: number | null;
    image: string;
  };
  favoritePlayer: number;
  valuePosition: string;
  rookieOrVets: "Rookies" | "Vets" | "Rookie" | string;
  philosophy: string;
  tradingScale: number;
  preferredContact: string;
  venmo: string;
}

// --- 2011-2017 HARDCODED HISTORY ---
export const MANUAL_ARCHIVES = [
  // 2023 TOILET BOWL OVERRIDE
  { year: 2023, type: 'toilet_bowl', manager: 'Landon' },

  { year: 2017, type: 'champion', manager: 'Tommy' },
  { year: 2017, type: 'runner_up', manager: 'JD' },
  { year: 2017, type: 'third_place', manager: 'Minnix' },
  { year: 2016, type: 'champion', manager: 'Tommy' },
  { year: 2016, type: 'runner_up', manager: 'Minnix' },
  { year: 2016, type: 'third_place', manager: 'Ray' },
  { year: 2015, type: 'champion', manager: 'Keith' },
  { year: 2015, type: 'runner_up', manager: 'JD' },
  { year: 2015, type: 'third_place', manager: 'Tommy' },
  { year: 2014, type: 'champion', manager: 'Garet' },
  { year: 2014, type: 'runner_up', manager: 'Gordie' },
  { year: 2014, type: 'third_place', manager: 'Keith' },
  { year: 2013, type: 'champion', manager: 'Tommy' },
  { year: 2013, type: 'runner_up', manager: 'Minnix' },
  { year: 2013, type: 'third_place', manager: 'Bryan' },
  { year: 2012, type: 'champion', manager: 'Bryan' },
  { year: 2012, type: 'runner_up', manager: 'Chris' },
  { year: 2012, type: 'third_place', manager: 'Nicholas' },
  { year: 2011, type: 'champion', manager: 'Gordie' },
  { year: 2011, type: 'runner_up', manager: 'Wade' },
  { year: 2011, type: 'third_place', manager: 'Zach' },
];

// --- NAME MAPPING ---
export const HISTORY_MAPPING: Record<string, string> = {
  "Tommy": "Tommy",
  "JD": "JD",
  "Ray": "Ray",
  "Wade": "Wade",
  "Travis": "Travis",
  "Minnix": "James",
  "Bryan": "Bryan",
  "Brian": "Brian",
  "Jordan": "Jordan",
  "Stan": "Stan",
  "Rashad": "Rashad",
  "Aaron": "Aaron",
  "Dave": "Dave",
  "Doug": "Doug",
  "Nudas Priest": "Aaron",
  "ETN' Deez Nutz": "Tommy",
  "MadPanda": "JD",
  "Gordie": "Gordie",
  "Keith": "Keith",
  "Garet": "Garet",
  "Chris": "Chris",
  "Landon": "Landon",
  "Zach": "Zach",
  "Nicholas": "Nicholas",
  "Patrick": "Patrick",
  "Rachel": "Rachel",
  "Darren": "Darren",
  "Ricky": "Ricky",
  "Billy": "Billy",
};

export const managers: Manager[] = [
  {
    roster: 1,
    name: "Ray",
    coOwner: "Jeffrey",
    location: "Richmond",
    bio: "Greatest Commish Ever (self-proclaimed). Wannabe paper champ. Bargain draft hunter. Trade wizard. The respectable half of Prestigio Mundial.",
    photo: getOwnerImagePath("ray-long"),
    fantasyStart: 2011,
    favoriteTeam: "atl",
    mode: "Rebuild",
    rival: { name: "Wade", link: 6, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 9509,
    valuePosition: "RB",
    rookieOrVets: "Vets",
    philosophy: "Make sure you have more money left than everyone else when the draft or season ends.",
    tradingScale: 8,
    preferredContact: "Text",
    venmo: "raylong"
  },
  {
    roster: 2,
    name: "JD",
    location: "Richmond",
    bio: "Husband, Father, Architect, Artist, DJ. Lost 4 Championships and only 1 W.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2012,
    favoriteTeam: "nyj",
    mode: "Win Now",
    rival: { name: "Tommy", link: 3, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 254,
    valuePosition: "WR",
    rookieOrVets: "Vets",
    philosophy: "To crush your enemies, see them driven before you, and to hear the lamentation of their women.",
    tradingScale: 5,
    preferredContact: "Sleeper",
    venmo: "jd-dowling"
  },
  {
    roster: 3,
    name: "Jordan",
    coOwner: "Landon",
    tookOver: 2017,
    location: "London",
    bio: "I’ve played fantasy since like 2010. I like bikepacking, tabletop games and video games.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2017,
    favoriteTeam: "min",
    mode: "Win Now",
    rival: { name: "Dave", link: 11, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 6794,
    valuePosition: "RB",
    rookieOrVets: "Vets",
    philosophy: "I’m not here for a long time. I’m here for a good time.",
    tradingScale: 7,
    preferredContact: "Text",
    venmo: "jordan-maslyn"
  },
  {
    roster: 4,
    name: "Tommy",
    location: "Shreveport",
    bio: "Therapist, Pastor, Avid Magic the Gathering player and historically successful fantasy footballer.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2012,
    favoriteTeam: "no",
    mode: "Dynasty",
    rival: { name: "Dave", link: 1, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 12481,
    valuePosition: "WR",
    rookieOrVets: "Vets",
    philosophy: "Trade every player with every owner and kick Dave’s ass.",
    tradingScale: 10,
    preferredContact: "Text",
    venmo: "tommy-moore"
  },
  {
    roster: 5,
    name: "Stan",
    tookOver: 2025,
    location: "Richmond",
    bio: "I am a huge sports fan. My favorite sports are football and hockey. I am also a huge wrestling fan. AEW and WWE BAY BAY!",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2025,
    favoriteTeam: "gb",
    mode: "Win Now",
    rival: { name: "Rashad", link: 8, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 8161,
    valuePosition: "RB",
    rookieOrVets: "Vets",
    philosophy: "Win BIG or go home!",
    tradingScale: 2,
    preferredContact: "Text",
    venmo: "stan-schoppe"
  },
  {
    roster: 6,
    name: "Wade",
    location: "Raleigh",
    bio: "One of the originals in this league and I'm usually fighting for my life to get into a wild card spot. I've been to three finals and won one.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2011,
    favoriteTeam: "car",
    mode: "Rebuild",
    rival: { name: "Tommy", link: 3, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 1181,
    valuePosition: "K",
    rookieOrVets: "Rookies",
    philosophy: "Pick good players, mostly.",
    tradingScale: 9,
    preferredContact: "Text",
    venmo: "wade-cameron"
  },
  {
    roster: 7,
    name: "Doug",
    tookOver: 2019,
    location: "Richmond",
    bio: "Assistant Principal. JMU alum (Go Dukes!) big college football fan. Perennial middle-of-the-pack fantasy owner.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2019,
    favoriteTeam: "nyg",
    mode: "Rebuild",
    rival: { name: "Dave", link: 11, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 12508,
    valuePosition: "RB",
    rookieOrVets: "Rookies",
    philosophy: "Draft well. Don't trade. Finish 6th.",
    tradingScale: 1,
    preferredContact: "Sleeper",
    venmo: "doug-fordham"
  },
  {
    roster: 8,
    name: "Travis",
    location: "Richmond",
    bio: "Born in Roanoke and have lived in Richmond since 2006. Married to my high school sweetheart and raising two boys. I love supporting my kids with the sports. I’m a big baseball fan, coaching, and flipping cards as a side hustle. I’ve been in the league and gotten more asswhopin’ than I’ve dished out. However, when you see that fat freckley face blow a kiss, then you know.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2012,
    favoriteTeam: "was",
    mode: "Win Now",
    rival: { name: "Ray", link: 0, image: getOwnerImagePath("ray-long") },
    favoritePlayer: 4137,
    valuePosition: "RB",
    rookieOrVets: "Vets",
    philosophy: "Don’t get voodoo-ed",
    tradingScale: 4,
    preferredContact: "Text",
    venmo: "travis-miller"
  },
  {
    roster: 9,
    name: "Rashad",
    tookOver: 2022,
    location: "Richmond",
    bio: "Drug lord and author of a series of children’s books.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2022,
    favoriteTeam: "was",
    mode: "Win Now",
    rival: { name: "Tommy", link: 3, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 3973,
    valuePosition: "WR",
    rookieOrVets: "Rookies",
    philosophy: "Score. Win. Don’t get hurt…..and most importanty FUCK TAYLOR SWIFT",
    tradingScale: 5,
    preferredContact: "Sleeper",
    venmo: "rashad-gresham"
  },
  {
    roster: 10,
    name: "Brian",
    location: "Columbus",
    bio: "Lorem ipsum...",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2016,
    favoriteTeam: "cle",
    mode: "Rebuild",
    rival: { name: "Tommy", link: 3, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 3973,
    valuePosition: "WR",
    rookieOrVets: "Rookie",
    philosophy: "Your fantasy team's philosophy",
    tradingScale: 8,
    preferredContact: "Text",
    venmo: "brian-stevens"
  },
  {
    roster: 11,
    name: "Aaron",
    tookOver: 2025,
    location: "Richmond",
    bio: "Coaching my sons youth sports teams",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2025,
    favoriteTeam: "sf",
    mode: "Win Now",
    rival: { name: "Stan", link: 4, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 5991,
    valuePosition: "WR",
    rookieOrVets: "Vets",
    philosophy: "Finish First or Last",
    tradingScale: 10,
    preferredContact: "Sleeper",
    venmo: "aaron-hawkins"
  },
  {
    roster: 12,
    name: "Dave",
    tookOver: 2019,
    location: "Richmond",
    bio: "I grow beards with dick like aromas",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2019,
    favoriteTeam: "det",
    mode: "Win Now",
    rival: { name: "Tommy", link: 3, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 12481,
    valuePosition: "RB",
    rookieOrVets: "Vets",
    philosophy: "Raw Dog Everybody",
    tradingScale: 7,
    preferredContact: "Text",
    venmo: "dave-besedich"
  },
  // --- DAMON (THE AUCTIONEER) ---
  {
    roster: 9999, // Fake ID
    name: "Damon",
    location: "Richmond",
    bio: "The legendary voice of the River City FFL draft. He doesn't own a team, but for one day a year, he owns all of us. Master of the gavel and drainer of wallets.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2017,
    favoriteTeam: "tb",
    mode: "Auctioneer",
    rival: { name: "Silence", link: null, image: DEFAULT_OWNER_IMAGE },
    favoritePlayer: 0,
    valuePosition: "Gavel",
    rookieOrVets: "Vets",
    philosophy: "Sold!",
    tradingScale: 10,
    preferredContact: "Phone",
    venmo: "damon-auctioneer"
  }
];

// --- RETIRED MANAGERS ---
export const retiredManagers: Manager[] = [
  {
    roster: 9001,
    name: "Landon Elliott",
    teamName: "Special Brownies",
    location: "Richmond",
    bio: "Former co-owner of 'The Special Brownies'. Retired league legend.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2012,
    favoriteTeam: "cle",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 3973,
    valuePosition: "QB",
    rookieOrVets: "Vets",
    philosophy: "I walked so Jordan could run.",
    tradingScale: 1,
    preferredContact: "Carrier Pigeon",
    venmo: ""
  },
  {
    roster: 9002,
    name: "Gordie Gahagan",
    teamName: "Freakshow Freaks",
    location: "Unknown",
    bio: "The Original Champion (2011). A founding father of the league. RIP.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2011,
    favoriteTeam: "gb",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "First to win it all.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9003,
    name: "Chris Barras",
    teamName: "Receding Zuerlein",
    location: "Unknown",
    bio: "League Creator. 2012 Runner-Up. A staple of the early league years.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2011,
    favoriteTeam: "tb",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "The Founder.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9004,
    name: "Garet Prior",
    teamName: "The Land of Cleve",
    location: "Unknown",
    bio: "2014 League Champion.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2013,
    favoriteTeam: "cle",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Veni, Vidi, Vici.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9005,
    name: "James Minnix",
    teamName: "Hyde the Russell Sprouts",
    location: "Unknown",
    bio: "Perennial contender. 3rd place twice (2013, 2017) and Runner-Up in 2016.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2012,
    favoriteTeam: "pit", // UPDATED: Changed from 'nfl' to 'pit'
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Always in the mix.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9006,
    name: "Rachel Woolard",
    teamName: "Zach's 2nd Team",
    location: "Unknown",
    bio: "Founding member of the league in 2011.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2011,
    favoriteTeam: "nfl",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "The First Lady of River City FFL.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9007,
    name: "Zach Woolard",
    location: "Unknown",
    bio: "Founding member. 3rd Place in 2011.",
    photo: "",
    fantasyStart: 2011,
    favoriteTeam: "nfl",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Original Gangster.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9008,
    name: "Ricky Taylor",
    teamName: "Ricky Crickets",
    location: "Unknown",
    bio: "Former league member.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2011,
    favoriteTeam: "was",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Part of the history.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9009,
    name: "Patrick Leahey",
    location: "Unknown",
    bio: "Competed in the 2017 season.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2017,
    favoriteTeam: "was",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Just happy to be here.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9010,
    name: "Bryan Doane",
    teamName: "Weeping Snowflakes",
    location: "Unknown",
    bio: "2012 League Champion. Defeated Chris in the finals.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2012,
    favoriteTeam: "was",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Champion of 2012.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9011,
    name: "Keith Polarek",
    teamName: "Team Polarek",
    location: "Unknown",
    bio: "2015 League Champion. Consistent contender in the early years.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2011,
    favoriteTeam: "was",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Win.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9012,
    name: "Darren Kusaj",
    location: "Unknown",
    bio: "Competed in the early years (2011-2012).",
    photo: "",
    fantasyStart: 2011,
    favoriteTeam: "nfl",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Early days.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9013,
    name: "Nicholas Bates",
    location: "Unknown",
    bio: "3rd Place finisher in 2012.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2012,
    favoriteTeam: "gb",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Brief but memorable.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  },
  {
    roster: 9014,
    name: "Billy Biddle",
    teamName: "Brilly",
    location: "Unknown",
    bio: "Former league member.",
    photo: DEFAULT_OWNER_IMAGE,
    fantasyStart: 2012,
    favoriteTeam: "atl",
    mode: "Retired",
    rival: { name: "River City FFL", link: null, image: "/River City FFL Logo.JPG" },
    favoritePlayer: 0,
    valuePosition: "Flex",
    rookieOrVets: "Vets",
    philosophy: "Here for the party.",
    tradingScale: 5,
    preferredContact: "Text",
    venmo: ""
  }
];
