import assert from "node:assert/strict";
import fs from "node:fs";

const x = JSON.parse(fs.readFileSync("data/current/draft-intelligence/2026.json", "utf8"));
const fail = [];
const check = (name, ok) => { if (!ok) fail.push(name); };
const ranked = x.picks.filter((p) => p.currentMarketRank !== null);
check("canonical_48", x.picks.length === 48 && new Set(x.picks.map((p) => p.actualOverallPick)).size === 48);
check("direction_positive_value", x.picks.filter((p) => p.marketValueDelta > 0).every((p) => p.marketClassification.includes("VALUE")));
check("direction_negative_reach", x.picks.filter((p) => p.marketValueDelta < 0).every((p) => p.marketClassification.includes("REACH") || p.marketClassification === "FAIR VALUE" || p.marketClassification === "MARKET UNCERTAIN"));
check("arithmetic", x.picks.every((p) => p.marketValueDelta === null || p.marketValueDelta === p.actualOverallPick - p.currentMarketRank));
check("no_legacy_sign", x.picks.every((p) => !Object.hasOwn(p, "pickDifference")));
check("confidence", x.picks.every((p) => ["HIGH", "LOW", "UNRANKED"].includes(p.marketConfidence)));
check("unranked_safe", x.picks.filter((p) => p.marketConfidence === "UNRANKED").every((p) => p.currentMarketRank === null && p.marketValueDelta === null && p.marketClassification === "MARKET UNCERTAIN"));
check("capital_adjusted", x.picks.every((p) => p.capitalAdjustedValue === null || typeof p.capitalAdjustedValue === "number"));
check("opportunity_direction", x.picks.every((p) => p.opportunityCost.betterRankedAlternatives.every((a) => a.rank < p.currentMarketRank && a.marketRankGap === p.currentMarketRank - a.rank)));
check("opportunity_available", x.picks.every((p) => p.opportunityCost.topThreeAvailable.every((a) => a.laterLccPick === null || a.laterLccPick > p.actualOverallPick)));
check("owner_aggregates", Object.values(x.owners).filter((o) => o.selectionCount).every((o) => o.marketValueCaptured === x.picks.filter((p) => p.ownerId === o.ownerId).reduce((s, p) => s + (p.marketValueDelta ?? 0), 0)));
check("separate_impact", Object.values(x.owners).every((o) => Object.hasOwn(o, "classImpact") && Object.hasOwn(o, "efficiencyPerCapital")));
check("methodology", x.gradeMethodology.marketDirection.formula === "actualOverallPick - currentMarketRank" && Math.abs(Object.values(x.gradeMethodology.recommendedWeights).reduce((a, b) => a + b, 0) - 1) < 0.001);
check("rubric_provisional", x.provisionalRubricTest.status === "PROVISIONAL_NOT_FOR_PUBLICATION");
check("no_final_grades", x.blockedFields.includes("FINAL_GRADES") && x.currentMarketDecision.finalGradesPublished === false);
check("may_separate", x.marketMovement.comparisonMode === "CURRENT_VS_MAY_EVIDENCE");
check("roast_levels", x.roastHooks.every((h) => ["STRONG ROAST", "LIGHT ROAST", "NO ROAST"].includes(h.confidence)));
assert.equal(fail.length, 0, fail.join(", "));
console.log(JSON.stringify({ status: x.status, checks: { canonical48: true, valueDirection: true, reachDirection: true, arithmetic: true, legacySignRemoved: true, confidence: true, unrankedSafe: true, capitalAdjusted: true, opportunityDirection: true, opportunityAvailable: true, ownerAggregates: true, separateClassImpact: true, rubricProvisional: true, noFinalGrades: true }, ranked: ranked.length, owners: Object.keys(x.owners).length, opportunities: x.opportunityCosts.length, strongRoasts: x.roastHooks.filter((h) => h.confidence === "STRONG ROAST").length, lightRoasts: x.roastHooks.filter((h) => h.confidence === "LIGHT ROAST").length }, null, 2));
