import assert from "node:assert/strict";
import fs from "node:fs";

const x = JSON.parse(fs.readFileSync("data/current/draft-intelligence/2026.json", "utf8"));
const fail = [];
const check = (name, ok) => { if (!ok) fail.push(name); };
const ranked = x.picks.filter((p) => p.currentMarketRank !== null);
check("canonical_48", x.picks.length === 48 && new Set(x.picks.map((p) => p.actualOverallPick)).size === 48);
check("direction_positive_value", x.picks.filter((p) => p.marketValueDelta > 0).every((p) => p.marketClassification.includes("VALUE")));
check("direction_negative_reach", x.picks.filter((p) => p.marketValueDelta < 0).every((p) => p.marketClassification.includes("REACH") || p.marketClassification === "FAIR VALUE" || p.marketClassification === "MARKET UNCERTAIN"));
check("arithmetic", x.picks.every((p) => p.marketValueDelta === null || p.marketValueDelta === p.actualOverallPick - p.lccPoolCurrentMarketRank));
check("no_legacy_sign", x.picks.every((p) => !Object.hasOwn(p, "pickDifference")));
check("confidence", x.picks.every((p) => ["HIGH", "LOW", "UNRANKED"].includes(p.marketConfidence)));
check("unranked_safe", x.picks.filter((p) => p.marketConfidence === "UNRANKED").every((p) => p.currentMarketRank === null && p.marketValueDelta === null && p.marketClassification === "MARKET UNCERTAIN"));
check("capital_adjusted", x.picks.every((p) => p.capitalAdjustedValue === null || typeof p.capitalAdjustedValue === "number"));
check("opportunity_direction", x.picks.every((p) => p.opportunityCost.betterRankedAlternatives.every((a) => a.rank < p.currentMarketRank && a.marketRankGap === p.currentMarketRank - a.rank)));
check("opportunity_available", x.picks.every((p) => p.opportunityCost.topThreeAvailable.every((a) => a.laterLccPick === null || a.laterLccPick > p.actualOverallPick)));
check("owner_aggregates", Object.values(x.owners).length === 12 && Object.values(x.owners).every((o) => Object.hasOwn(o, "averageNormalizedDelta") && Object.hasOwn(o, "capitalWeightedMarketResult")));
check("separate_impact", Object.values(x.owners).every((o) => Object.hasOwn(o, "capitalWeightedMarketResult")) && Object.keys(x.classImpactComponents ?? {}).length === 12);
check("methodology", x.gradeMethodology.marketDirection.formula === "actualOverallPick - currentMarketRank" && Math.abs(Object.values(x.gradeMethodology.recommendedWeights).reduce((a, b) => a + b, 0) - 1) < 0.001);
check("rubric_provisional", x.provisionalRubricTest.status === "PROVISIONAL_NOT_FOR_PUBLICATION");
check("no_final_grades", x.blockedFields.includes("FINAL_GRADES") && x.currentMarketDecision.finalGradesPublished === false);
check("may_separate", x.marketMovement.comparisonMode === "CURRENT_VS_MAY_EVIDENCE");
check("roast_levels", x.roastHooks.every((h) => ["STRONG ROAST", "LIGHT ROAST", "NO ROAST"].includes(h.confidence)));
check("normalized_primary", x.picks.every((p) => Object.hasOwn(p, "lccPoolCurrentMarketRank") && Object.hasOwn(p, "marketAgreement") && Object.hasOwn(p, "marketConfidenceMultiplier") && Object.hasOwn(p, "capitalWeightedMarketImpact") && Object.hasOwn(p, "normalizedOpportunityCost")));
check("confidence_multiplier", x.picks.every((p) => [0, 0.35, 0.6, 1].includes(p.marketConfidenceMultiplier)));
check("normalized_opportunity", x.opportunityCosts.every((o) => o.marketRankGap >= 8 && o.alternativeConfidence === "HIGH" && o.alternativeRank < o.selectedNormalizedRank));
check("separate_grade_impact", x.provisionalRubricTest.provisionalDraftGradeOrdering.length === 12 && x.provisionalRubricTest.provisionalClassImpactOrdering.length === 12);
check("market_scale_audit", x.marketScaleAudit?.status === "N2.3A_MARKET_SCALE_AUDIT_COMPLETE_NO_RUBRIC_CHANGE");
check("raw_universe_documented", x.marketScaleAudit?.rawUniverses?.fpTrack?.observedRows > 0 && x.marketScaleAudit?.rawUniverses?.fantasyOrphans?.observedRows > 0);
check("normalized_universe_documented", x.marketScaleAudit?.normalizedBoard?.boardSize === x.marketScaleAudit?.rawUniverses?.combinedUniqueRows);
check("omitted_players_documented", Array.isArray(x.marketScaleAudit?.omittedPlayers));
check("eligible_undrafted_preserved", x.marketScaleAudit?.normalizedBoard?.removalPolicy === "REMOVE_NONE");
check("source_disagreement_preserved", x.picks.every((p) => Object.hasOwn(p, "sourceSpecificRanks") && Object.hasOwn(p, "sourceSpread")));
check("source_disagreement_reduces_scale_confidence", x.picks.filter((p) => p.sourceSpread >= 8).every((p) => p.scaleAuditConfidence === "REDUCED_FOR_SCALE_DISAGREEMENT"));
check("retrospective_label", x.marketScaleAudit?.scaleDecision?.retrospectiveLabel?.includes("CURRENT_MARKET_RETROSPECTIVE"));
assert.equal(fail.length, 0, fail.join(", "));
console.log(JSON.stringify({ status: x.status, checks: { canonical48: true, valueDirection: true, reachDirection: true, arithmetic: true, legacySignRemoved: true, confidence: true, unrankedSafe: true, capitalAdjusted: true, opportunityDirection: true, opportunityAvailable: true, ownerAggregates: true, separateClassImpact: true, rubricProvisional: true, noFinalGrades: true }, ranked: ranked.length, owners: Object.keys(x.owners).length, opportunities: x.opportunityCosts.length, strongRoasts: x.roastHooks.filter((h) => h.confidence === "STRONG ROAST").length, lightRoasts: x.roastHooks.filter((h) => h.confidence === "LIGHT ROAST").length }, null, 2));
