import fs from 'node:fs';

const recapPath = 'data/current/draft-intelligence/2026-recap-draft.json';
const intelligencePath = 'data/current/draft-intelligence/2026.json';
const recap = JSON.parse(fs.readFileSync(recapPath, 'utf8'));
const intelligence = JSON.parse(fs.readFileSync(intelligencePath, 'utf8'));
const checks = {};
const check = (name, value) => { checks[name] = Boolean(value); };
const owners = recap.teamReportCards;
const lockedOwners = intelligence.ownerGrades;
const lockedByName = new Map(lockedOwners.map((owner) => [owner.ownerName, owner]));
const gradeOrder = [...owners].sort((a, b) => a.draftGradeRank - b.draftGradeRank).map((owner) => owner.owner);
check('correct2026Artifact', recapPath.endsWith('/2026-recap-draft.json') && recap.season === 2026);
check('publicationStatus', recap.publicationStatus === 'PUBLIC');
check('exactly12OwnerCards', owners.length === 12 && new Set(owners.map((owner) => owner.owner)).size === 12);
check('gradeOrderingMatchesLockedArtifact', owners.every((owner) => lockedByName.get(owner.owner)?.draftGradeRank === owner.draftGradeRank) && gradeOrder.join('|') === [...lockedOwners].sort((a, b) => a.draftGradeRank - b.draftGradeRank).map((owner) => owner.ownerName).join('|'));
check('gradesPreserved', owners.every((owner) => lockedByName.get(owner.owner)?.provisionalLetterGrade === owner.grade));
check('earlDraftGrade1', owners.find((owner) => owner.owner === 'Earl Perkins')?.draftGradeRank === 1);
const lockedEfficiency = Object.values(intelligence.ownerMarketEfficiency);
check('tyroneMarketEfficiency1', owners.find((owner) => owner.owner === 'Tyrone Poist')?.marketEfficiencyRank === 1 && lockedEfficiency.sort((a, b) => b.efficiencyPerCapital - a.efficiencyPerCapital)[0]?.ownerName === 'Tyrone Poist');
check('tyroneClassImpact1', owners.find((owner) => owner.owner === 'Tyrone Poist')?.classImpactRank === 1);
check('rayRanksPreserved', owners.find((owner) => owner.owner === 'Ray Long')?.draftGradeRank === 8 && owners.find((owner) => owner.owner === 'Ray Long')?.classImpactRank === 3);
check('valuesPreserved', JSON.stringify(recap.valueLeaderboard.entries.map((entry) => [entry.player, entry.delta])) === JSON.stringify([['Adam Randall', 7], ['Max Klare', 5], ['Emmett Johnson', 4], ['Elijah Sarratt', 3], ['Brenen Thompson', 3], ['Denzel Boston', 3], ['Demond Claiborne', 2], ['Antonio Williams', 2]]));
check('reachesPreserved', JSON.stringify(recap.reachLeaderboard.entries.map((entry) => [entry.player, entry.delta])) === JSON.stringify([['Jack Endries', -11], ['Roman Hemby', -11], ['Zavion Thomas', -10], ['Cade Klubnik', -10], ['Garrett Nussmeier', -10], ['Jam Miller', -8]]));
const keithCard = owners.find((owner) => owner.owner === 'Keith Winder');
check('noStaleNussmeierOpportunityCost', keithCard?.copy.includes('no numeric same-position Opportunity Cost claim attached to that pick') && !keithCard.copy.includes('Mike Washington Jr.'));
check('exactly8PublicAwards', recap.awards.length === 8);
check('noWithheldAwardsRendered', !('withheldAwards' in recap) && !recap.awards.some((award) => /NONE|WITHHELD/i.test(JSON.stringify(award))));
check('wrRunPicks12to17', JSON.stringify(recap.wrRun.picks.map((pick) => pick.pick)) === JSON.stringify([12, 13, 14, 15, 16, 17]));
check('receiptsSavedFutureRegradePresent', recap.futureRegrade.includes('permanent historical checkpoint') && recap.futureRegrade.includes('three years later'));
check('noLiveMarketRuntimeFetch', !fs.readFileSync('components/drafts/RookieDraftRecap.tsx', 'utf8').includes('fetch('));
check('frozenCheckpointArtifact', fs.readFileSync('components/drafts/RookieDraftRecap.tsx', 'utf8').includes("@/data/current/draft-intelligence/2026-recap-draft.json"));
check('routePresent', fs.existsSync('app/league-info/drafts/2026-recap/page.tsx'));
const passed = Object.values(checks).every(Boolean);
console.log(JSON.stringify({ status: passed ? 'PASS' : 'FAIL', checks, recapPath, publicAwardCount: recap.awards.length }, null, 2));
if (!passed) process.exit(1);
