import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const page = await readFile("app/trade-analyzer/page.tsx", "utf8");
const client = await readFile("app/trade-analyzer/TradeAnalyzerParticipantClient.tsx", "utf8");
const api = await readFile("app/api/trade-analyzer/analyze/route.ts", "utf8");
const docs = await readFile("docs/trade-analyzer-ui-prototype-v1.md", "utf8");
const required = (text, values, label) => values.forEach((value) => assert.ok(text.includes(value), `${label} missing ${value}`));
required(page, ["getCurrentMemberSession", "TRADE_ANALYZER_FEATURE_ENABLED", "TRADE_ANALYZER_PRIVATE_OUTPUT_APPROVED", "TradeAnalyzerParticipantClient"], "page");
required(client, ["League Trade", "Trade Sandbox", "Participant 1", "Participant 2", "Choose a franchise", "ParticipantColumn", "Draft picks", "DraftPickGroups", "sideA: { assetIds: packageA }", "sideB: { assetIds: packageB }", "/api/trade-analyzer/analyze", "< 15", "Swap Teams", "Reset Trade", "Fairness unavailable", "Provisional"], "client");
assert.equal((client.match(/Participant [12]/g) ?? []).length >= 2, true, "two participants present");
assert.equal(client.includes("ownerId === teamA"), true, "league ownership filtering present");
assert.equal(client.includes("mode === \"LEAGUE\" && asset.ownerId !== ownerId"), true, "league ownership restriction present");
assert.equal(client.includes("setTeamA(\"\")"), true, "participant one starts unselected");
assert.equal(client.includes("setTeamB(\"\")"), true, "participant two starts unselected");
assert.equal(client.includes("defaultOwnerId"), false, "authenticated owner is not preselected");
assert.equal(client.includes("Current franchise assets"), false, "shared league asset section remains");
assert.equal(client.includes("asset.ownerId !== ownerId"), true, "league ownership enforcement present");
assert.equal(client.includes("Draft picks"), true, "draft picks follow roster in participant column");
assert.equal(client.includes("border-[var(--lcc-brand-primary)]"), true, "selected row treatment present");
assert.equal(client.includes("Participant 3"), false, "multi-team participant exposed");
assert.equal(client.includes("Random"), false, "random trade control exposed");
assert.equal(client.includes("fairnessEngine"), false, "client imports fairness engine");
assert.equal(client.includes("currentValuationAdapter"), false, "client imports valuation adapter");
assert.equal(client.includes("tradeAnalysisService"), false, "client imports internal service");
assert.equal(client.includes("Save Trade"), false, "client exposes save control");
assert.equal(client.includes("Share Trade"), false, "client exposes share control");
assert.equal(client.includes("Winner"), false, "client exposes winner language");
assert.equal(client.includes("Consolidation"), false, "client exposes consolidation UI");
assert.equal(client.includes("item.marketShare.display * 100"), false, "client multiplies display percentage twice");
const formatShare = (display) => `${display.toFixed(1)}%`;
assert.equal(formatShare(41), "41.0%", "Side A market share presentation");
assert.equal(formatShare(59), "59.0%", "Side B market share presentation");
assert.equal(Number(formatShare(41).replace("%", "")) + Number(formatShare(59).replace("%", "")), 100, "display shares total 100");
required(api, ["outputMode", "TRADE_ANALYZER_FEATURE_ENABLED", "TRADE_ANALYZER_PRIVATE_OUTPUT_APPROVED"], "API");
required(docs, ["/trade-analyzer", "feature gate", "private-output", "Suppressed", "mobile", "deferred"], "documentation");
console.log("TRADE_UI_DIAGNOSTICS_PASS");
