import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const page = await readFile("app/trade-analyzer/page.tsx", "utf8");
const client = await readFile("app/trade-analyzer/TradeAnalyzerParticipantClient.tsx", "utf8");
const multi = await readFile("app/trade-analyzer/MultiTeamTradeAnalyzerClient.tsx", "utf8");
const api = await readFile("app/api/trade-analyzer/analyze/route.ts", "utf8");
const rosterImpact = await readFile("app/trade-analyzer/RosterImpactPanel.tsx", "utf8");
const analysisDetails = await readFile("app/trade-analyzer/AnalysisDetails.tsx", "utf8");
const docs = await readFile("docs/trade-analyzer-ui-prototype-v1.md", "utf8");
const multiDocs = await readFile("docs/trade-analyzer-multi-team-model-v1.md", "utf8");
const required = (text, values, label) => values.forEach((value) => assert.ok(text.includes(value), `${label} missing ${value}`));
required(page, ["getCurrentMemberSession", "TRADE_ANALYZER_FEATURE_ENABLED", "TRADE_ANALYZER_PRIVATE_OUTPUT_APPROVED", "TradeAnalyzerParticipantClient"], "page");
required(client, ["League Trade", "Trade Sandbox", "Participant 1", "Participant 2", "Choose a franchise", "ParticipantColumn", "Draft picks", "DraftPickGroups", "sideA: { assetIds: packageA, ownerId", "sideB: { assetIds: packageB, ownerId", "/api/trade-analyzer/analyze", "< 15", "Swap Teams", "Reset Trade", "Fairness unavailable", "PROVISIONAL"], "client");
assert.equal((client.match(/Participant [12]/g) ?? []).length >= 2, true, "two participants present");
assert.equal(client.includes("ownerId === teamA"), true, "league ownership filtering present");
assert.equal(client.includes("mode === \"LEAGUE\" && asset.ownerId !== ownerId"), true, "league ownership restriction present");
assert.equal(client.includes("setTeamA(\"\")"), true, "participant one starts unselected");
assert.equal(client.includes("setTeamB(\"\")"), true, "participant two starts unselected");
assert.equal(client.includes("defaultOwnerId"), false, "authenticated owner is not preselected");
assert.equal(client.includes("Current franchise assets"), false, "shared league asset section remains");
assert.equal(client.includes("asset.ownerId !== ownerId"), true, "league ownership enforcement present");
required(client, ["StickyAnalyze", "IntersectionObserver", "analyzeButtonRef", "topAnalyzeVisible", "packageIds.length > 0", "otherSelected > 0", "primaryName", "secondaryName", "primaryCount", "secondaryCount", "primaryCount === 1 ? \"asset\" : \"assets\""], "sticky analyze control");
required(client, ["resultRef", "requestAnimationFrame", "scrollIntoView", "prefers-reduced-motion", "preventScroll: true", "[result, error]", "TradeReportHeroView", "LCC Trade Analyzer", "Current Market Value Split", "Market Value Edge", "Fairness measures how closely", "consolidation effects", "Trade Summary", "Package Details", "AnalysisDetails", "VALUE UNAVAILABLE", "valuationPolicyVersion", "fairnessModelVersion"], "result discovery and report hero");
assert.equal(client.includes("resultRef.current"), true, "result anchor is used for discovery");
assert.equal((client.match(/scrollIntoView/g) ?? []).length, 1, "result discovery has one scroll path");
assert.equal(client.includes("[result, error]"), true, "result discovery responds to completed result or error state");
assert.equal(client.includes("onClick={analyze}"), true, "normal Analyze uses shared handler");
assert.equal(client.includes("onAnalyze={onAnalyze}"), true, "sticky Analyze uses shared handler prop");
assert.equal(client.includes("side === \"A\" && packageIds.length > 0"), true, "sticky control is league participant one scoped");
assert.equal(client.includes("fixed inset-x-3 bottom-3"), true, "sticky control is fixed to the viewport bottom");
assert.equal(client.includes("env(safe-area-inset-bottom)"), true, "sticky control accounts for mobile safe area");
assert.equal(client.includes("onClick={analyze}"), true, "top analyze button uses analyze handler");
assert.equal(client.includes("onAnalyze={analyze}"), true, "sticky receives analyze handler");
assert.equal(client.includes("onClick={onAnalyze}"), true, "sticky uses received analyze handler");
assert.equal(client.includes("querySelector"), false, "sticky implementation does not query the DOM");
assert.equal(client.includes(".click()"), false, "sticky implementation does not programmatically click");
assert.equal(client.includes("dispatchEvent"), false, "sticky implementation does not dispatch synthetic events");
assert.equal(client.includes("marketValue"), true, "existing market values remain available outside sticky control");
assert.equal((client.match(/fetch\(\"\/api\/trade-analyzer\/analyze/g) ?? []).length, 1, "sticky control does not add a second analyze fetch");
assert.equal(client.includes("aria-label=\"Analyze selected trade\""), true, "sticky control is labeled for assistive technology");
assert.equal(client.includes("Draft picks"), true, "draft picks follow roster in participant column");
assert.equal(client.includes("border-[var(--lcc-brand-primary)]"), true, "selected row treatment present");
assert.equal(client.includes("action={selected.has(asset.assetId) ? \"Remove\" : \"Select\"}"), true, "selected roster rows remove directly");
assert.equal(client.includes("asset.assetType === \"PICK\" ? \"Pick\""), true, "pick rows avoid redundant draft-capital text");
assert.equal(client.includes("item.marketShare.display * 100"), false, "market share is not multiplied twice");
assert.equal(client.includes('mode === "LEAGUE" && participantCount === 2'), true, "participant control is league-only");
assert.equal(client.includes(': ["Package A", "Package B"]'), true, "sandbox package terminology");
required(client, ["Search roster and picks", "Search by player, pick, or team", "SandboxAssetRow", "imageUrl", "nflTeam", "rosterStatus", "Add A", "Add B", "Remove A", "Remove B", "PackageSummary", "packageA={packageA}", "packageB={packageB}", "sandboxMatches", "discoveryActive", "slice(0, 25)", "max-h-[34rem]", "Showing first 25 results. Refine your search.", "Search for a player or choose a position to browse available assets.", "pickYear", "All Years"], "sandbox asset picker");
assert.equal(client.includes("discoveryActive ? <>") || client.includes("discoveryActive ?"), true, "blank sandbox does not render catalog");
assert.equal(client.includes("resultCount > 25"), true, "sandbox result cap is disclosed");
assert.equal(client.includes("catalog={catalog} onRemove"), true, "sandbox summaries use full catalog");
assert.equal(client.includes("disabled={selected && selectedSide !== \"A\"}"), true, "sandbox duplicate prevention");
assert.equal(client.includes("selected && asset.marketValue !== undefined"), true, "sandbox only shows selected values");
assert.equal(client.includes('primaryName="Package A"'), true, "sandbox sticky analyze labels");
assert.equal(client.includes("!hasResult}"), true, "sandbox sticky hides after result");
assert.equal(client.includes("!hasResult}") && (client.match(/!hasResult/g) ?? []).length >= 2, true, "league sticky hides after result");
required(client, ["rosterImpact", "RosterImpactPanel", "validateOwnership: mode === \"LEAGUE\""], "roster impact integration and sticky lifecycle");
required(multi, ["participants.length < 4", "addParticipant", "Remove Participant", "destinationFranchiseId", "Choose destination", "Multi-Team Trade Fairness", "Market Value Change", "Trade Routing", "Sends Value", "Receives Value", "current market value exchanged by every participant", "Team need", "consolidation effects", "future performance", "!result", "RosterImpactPanel"], "multi-team client");
assert.equal(client.includes("MultiTeamTradeAnalyzerClient"), true, "participant client exposes multi-team mode");
assert.equal(multi.includes("Winner") || multi.includes("Loser") || multi.includes("recommend"), false, "multi-team UI uses neutral market language");
assert.equal(multi.includes("received share"), false, "received share is not primary UI copy");
required(multi, ["Sends", "Receives", "net gain", "net loss", "→", "←", "sent by", "received by", "Market Value Change is the difference"], "multi-team result interpretation");
assert.equal(multi.includes("fairnessScore.toFixed"), true, "multi-team score is rendered from API result");
assert.equal(multi.includes("calculateMultiTeamFairness"), false, "multi-team client does not calculate fairness");
assert.equal(multi.includes("fetch(\"/api/trade-analyzer/analyze"), true, "multi-team UI uses the existing analysis endpoint");
assert.equal(client.includes("Participant 3"), true, "multi-team participant entry exposed");
assert.equal(client.includes("Random"), false, "random trade control exposed");
assert.equal(client.includes("fairnessEngine"), false, "client imports fairness engine");
assert.equal(client.includes("currentValuationAdapter"), false, "client imports valuation adapter");
assert.equal(client.includes("tradeAnalysisService"), false, "client imports internal service");
assert.equal(client.includes("Save Trade"), false, "client exposes save control");
assert.equal(client.includes("Share Trade"), false, "client exposes share control");
assert.equal(client.includes("Winner"), false, "client exposes winner language");
assert.equal(client.includes("Consolidation"), false, "client exposes consolidation UI");
assert.equal(client.includes("item.marketShare.display * 100"), false, "client multiplies display percentage twice");
required(client, ["Trade Summary", "sends ${sent} and receives ${received}.", "LCC Trade Analyzer", "trade.fairnessScore", "trade?.fairnessBand", "Current Market Value Split", "sideA.marketShare.display", "Package Details", "Sends", "Receives", "asset.baseValue", "VALUE UNAVAILABLE", "AnalysisDetails", "result.snapshot?.snapshotDate", "valuationPolicyVersion", "fairnessModelVersion", "PROVISIONAL"], "trade report");
assert.equal(client.includes("trade?.fairnessScore?.display"), true, "fairness score is rendered from API result");
assert.equal(client.includes("trade?.fairnessBand"), true, "fairness band is rendered from API result");
assert.equal(client.includes("style={{ width: `${sideA.marketShare.display}%` }}"), true, "market split uses API display percentage");
assert.equal(client.includes("style={{ width: `${sideB.marketShare.display}%` }}"), true, "second market split uses API display percentage");
assert.equal(client.includes("rawValue +"), false, "package presentation does not calculate totals");
assert.equal(client.includes("marketShare.display *"), false, "package presentation does not recalculate market share");
assert.equal(client.includes("Winner"), false, "trade report does not expose winner terminology");
assert.equal(client.includes("recommend"), false, "trade report does not expose recommendation language");
assert.equal(client.includes("auction"), false, "trade report does not expose River City auction fields");
assert.equal(client.includes("ADP"), false, "trade report does not expose River City ADP fields");
assert.equal(client.includes("querySelector"), false, "client has no indirect DOM action wiring");
assert.equal(client.includes(".click()"), false, "client has no programmatic click wiring");
assert.equal((client.match(/fetch\(\"\/api\/trade-analyzer\/analyze/g) ?? []).length, 1, "trade report adds no fetch path");
const formatShare = (display) => `${display.toFixed(1)}%`;
assert.equal(formatShare(41), "41.0%", "Side A market share presentation");
assert.equal(formatShare(59), "59.0%", "Side B market share presentation");
assert.equal(Number(formatShare(41).replace("%", "")) + Number(formatShare(59).replace("%", "")), 100, "display shares total 100");
required(api, ["outputMode", "TRADE_ANALYZER_FEATURE_ENABLED", "TRADE_ANALYZER_PRIVATE_OUTPUT_APPROVED"], "API");
required(api, ["One or more selected assets are no longer available."], "safe API error detail");
required(rosterImpact, ["Roster Impact", "participant.status", "market fairness", "Draft picks have no immediate lineup impact"], "roster-impact fallback UI");
required(analysisDetails, ["Analysis Details", "aria-expanded", "setExpanded", "Data Snapshot", "Evidence Quality", "Result Status", "Valuation Model", "Fairness Model"], "analysis details disclosure");
assert.equal(client.includes("Source approval is still pending"), false, "governance warning is not ordinary owner-facing copy");
required(docs, ["/trade-analyzer", "feature gate", "private-output", "Suppressed", "mobile", "deferred"], "documentation");
required(multiDocs, ["fairness-v1", "fairness-multi-v1", "netDelta", "routing", "consolidation", "roster fit", "performance"], "multi-team documentation");
console.log("TRADE_UI_DIAGNOSTICS_PASS");
