import { createTradeAnalyzerPostHandler } from "../app/api/trade-analyzer/analyze/route.ts";
import { BestEffortRateLimiter } from "../lib/trade-analyzer/tradeAnalyzerRouteSupport.ts";
import { requestOriginAllowed } from "../lib/trade-analyzer/tradeAnalyzerRouteSupport.ts";
import { analyzeTradeInternal } from "../lib/trade-analyzer/tradeAnalysisService.ts";
import type { CurrentAssetCatalog, CurrentCatalogAsset } from "../lib/trade-analyzer/types.ts";
import type { LccMemberSession } from "../lib/auth/types.ts";

const checks: { name: string; pass: boolean; detail: string }[] = [];
const check = (name: string, pass: boolean, detail: string) => checks.push({ name, pass, detail });
process.env.NEXT_PUBLIC_APP_URL ??= "https://long-country-club-ffl.web.app";
const asset = (id: string, value: number): CurrentCatalogAsset => ({ assetId: id, assetType: "PLAYER", displayName: id, position: "WR", baseValue: value, valueStatus: "VALUED", valueMethod: "FANTASYCALC_DIRECT", sourceName: "FantasyCalc", sourceRowId: id, snapshotDate: "2026-08-26", evidence: "HIGH", ownerId: "active-owner" });
const assets = [asset("a", 5000), asset("b", 4500), asset("c", 3000), asset("d", 2500), asset("e", 1500), asset("f", 1000)];
const catalog: CurrentAssetCatalog = { snapshotDate: "2026-08-26", assets, byAssetId: Object.fromEntries(assets.map((item) => [item.assetId, item])), integrity: { valid: true, errors: [] } };
const runtime = { catalog, snapshot: { date: "2026-08-26", sourceName: "FantasyCalc", sourceUrl: "https://example.invalid/source", retrievedAt: "2026-08-26T00:00:00.000Z", sourceLicenseStatus: "APPROVED", integrityValid: true } };
const member = (ownerId = "active-owner"): LccMemberSession => ({ identity: { uid: `${ownerId}-uid`, email: `${ownerId}@example.invalid`, name: ownerId, picture: null }, member: { memberId: ownerId, ownerId, displayName: ownerId, teamName: "Test Team", capabilities: [] } });
const unauthenticated = (): Promise<LccMemberSession | null> => Promise.resolve(null);
const enabled = { featureEnabled: () => true, licenseApproved: () => true, loadRuntime: async () => runtime, getSession: async () => member(), now: () => new Date("2026-08-26T12:00:00.000Z") };
const request = (body: string, init: RequestInit = {}) => new Request("http://localhost/api/trade-analyzer/analyze", { method: "POST", headers: { "content-type": "application/json", origin: "https://long-country-club-ffl.web.app" }, body, ...init });
const json = (sideA = ["a"], sideB = ["b"], extra: Record<string, unknown> = {}) => JSON.stringify({ sideA: { assetIds: sideA }, sideB: { assetIds: sideB }, ...extra });
const bodyOf = async (response: Response) => response.text();
const responseOf = async (handler: ReturnType<typeof createTradeAnalyzerPostHandler>, body: string, init?: RequestInit) => handler(request(body, init));

const featureOff = await responseOf(createTradeAnalyzerPostHandler({ getSession: async () => member(), featureEnabled: () => false, licenseApproved: () => true, loadRuntime: async () => runtime }), json());
const licenseOff = await responseOf(createTradeAnalyzerPostHandler({ ...enabled, licenseApproved: () => false }), json());
const privateOn = await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a"], ["b"], { validateOwnership: true }));
check("feature_off", featureOff.status === 403 && !(await bodyOf(featureOff)).includes("5000"), "FEATURE_NOT_AVAILABLE blocks without values");
check("license_off", licenseOff.status === 403 && !(await bodyOf(licenseOff)).includes("5000"), "SOURCE_LICENSE_UNAPPROVED blocks without values");
const privateBody = await bodyOf(privateOn);
check("private_on", privateOn.status === 200 && privateBody.includes('"ok":true') && privateBody.includes('"fairnessScore"'), "enabled local active-member request returns analysis");
const rosterImpactUnavailable = await responseOf(createTradeAnalyzerPostHandler(enabled), JSON.stringify({ sideA: { assetIds: ["a"], ownerId: "current-roster-unavailable" }, sideB: { assetIds: ["b"], ownerId: "current-roster-unavailable-b" }, validateOwnership: false }));
const rosterImpactUnavailableBody = JSON.parse(await bodyOf(rosterImpactUnavailable));
check("roster_impact_non_blocking", rosterImpactUnavailable.status === 200 && rosterImpactUnavailableBody.ok === true && rosterImpactUnavailableBody.data.rosterImpact?.participants.every((participant: { status: string }) => participant.status === "INCOMPLETE"), "valid market analysis remains available when roster impact is incomplete");
check("auth_matrix", (await responseOf(createTradeAnalyzerPostHandler({ ...enabled, getSession: unauthenticated }), json())).status === 401 && (await responseOf(createTradeAnalyzerPostHandler({ ...enabled, getSession: async () => ({ ...member(), member: null }) }), json())).status === 403 && (await responseOf(createTradeAnalyzerPostHandler({ ...enabled, getSession: async () => member("commissioner") }), json())).status === 200, "unauthenticated/unknown/retired deny; active and commissioner allow");
check("method", (await createTradeAnalyzerPostHandler(enabled)(new Request("http://localhost/api/trade-analyzer/analyze", { method: "GET" }))).status === 405, "GET cannot calculate");
check("content_type", (await responseOf(createTradeAnalyzerPostHandler(enabled), json(), { headers: { "content-type": "text/plain", origin: "https://long-country-club-ffl.web.app" } })).status === 415 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(), { headers: { "content-type": "application/json; charset=utf-8", origin: "https://long-country-club-ffl.web.app" } })).status === 200, "JSON required; charset accepted");
check("body_limit", (await responseOf(createTradeAnalyzerPostHandler(enabled), "x".repeat(16 * 1024 + 1))).status === 413, "16 KB body limit");
check("malformed_json", (await responseOf(createTradeAnalyzerPostHandler(enabled), "{bad")).status === 400, "malformed JSON returns 400");
check("schema_limits", (await responseOf(createTradeAnalyzerPostHandler(enabled), json([], ["b"]))).status === 400 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(Array.from({ length: 16 }, (_, index) => String(index)), ["b"]))).status === 400 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a"], ["b"], { ownerId: "spoofed" }))).status === 400, "empty, oversized, and unexpected fields rejected");
check("spoofing", (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a"], ["b"], { baseValue: 999999, snapshot: "fake", modelVersion: "fake" }))).status === 400, "client value/snapshot/model spoofing rejected");
check("duplicates", (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a", "a"], ["b"]))).status === 400 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a"], ["a"]))).status === 400 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["unknown"], ["b"]))).status === 400, "duplicate and unknown assets rejected");
const unknownResponse = await responseOf(createTradeAnalyzerPostHandler(enabled), json(["unknown"], ["b"]));
const unknownBody = await bodyOf(unknownResponse);
check("safe_error_detail", unknownResponse.status === 400 && unknownBody.includes("selected assets are no longer available") && !unknownBody.includes("at /"), "deterministic validation errors map to safe owner-facing messages");
check("origin", (await responseOf(createTradeAnalyzerPostHandler(enabled), json(), { headers: { "content-type": "application/json", origin: "https://evil.example" } })).status === 403, "cross-origin request rejected");
const proxiedOriginRequest = new Request("https://ssrlongcountryclubffl-tfhicrqlta-uc.a.run.app/api/trade-analyzer/analyze", { method: "POST", headers: { "content-type": "application/json", origin: "https://long-country-club-ffl.web.app" }, body: json() });
check("firebase_proxy_origin", requestOriginAllowed(proxiedOriginRequest) && (await createTradeAnalyzerPostHandler(enabled)(proxiedOriginRequest)).status === 200, "canonical Hosting Origin is accepted when request.url is the internal SSR origin");
const missingOriginRequest = new Request("https://ssrlong-country-club-ffl-tfhicrqlta-uc.a.run.app/api/trade-analyzer/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: json() });
check("missing_origin", !requestOriginAllowed(missingOriginRequest), "missing Origin fails closed");
const previousConfiguredOrigin = process.env.NEXT_PUBLIC_APP_URL;
process.env.NEXT_PUBLIC_APP_URL = "https://wrong.example";
check("configured_origin_mismatch", !requestOriginAllowed(proxiedOriginRequest), "mismatched configured origin is rejected");
process.env.NEXT_PUBLIC_APP_URL = previousConfiguredOrigin;
const spoofedForwardedHostRequest = new Request("https://ssrlongcountryclubffl-tfhicrqlta-uc.a.run.app/api/trade-analyzer/analyze", { method: "POST", headers: { "content-type": "application/json", origin: "https://long-country-club-ffl.web.app", host: "evil.example", "x-forwarded-host": "evil.example", "x-forwarded-proto": "http" }, body: json() });
check("forwarded_host_not_authority", requestOriginAllowed(spoofedForwardedHostRequest), "Host and forwarded headers do not override configured Origin authority");
const telemetryLines: string[] = [];
const originalConsoleInfo = console.info;
console.info = (...args: unknown[]) => telemetryLines.push(args.map(String).join(" "));
const multiTelemetry = async (value: Record<string, unknown>, handler = createTradeAnalyzerPostHandler(enabled)) => { telemetryLines.length = 0; const response = await handler(request(JSON.stringify(value))); await response.text(); return telemetryLines.join("\n"); };
const circularParticipants = (ids: string[], assetsByIndex = ids.map((_, index) => String.fromCharCode(97 + index)), destinations = ids.map((_, index) => ids[(index + 1) % ids.length])) => ({ participants: ids.map((franchiseId, index) => ({ franchiseId, outgoingAssets: [{ assetId: assetsByIndex[index], destinationFranchiseId: destinations[index] }] })) });
const emptyTelemetry = await multiTelemetry({ participants: [{ franchiseId: "A", outgoingAssets: [] }, { franchiseId: "B", outgoingAssets: [{ assetId: "b", destinationFranchiseId: "A" }] }, { franchiseId: "C", outgoingAssets: [{ assetId: "c", destinationFranchiseId: "A" }] }] });
const invalidDestinationTelemetry = await multiTelemetry(circularParticipants(["A", "B", "C"], ["a", "b", "c"], ["B", "Unknown", "A"]));
const selfDestinationTelemetry = await multiTelemetry(circularParticipants(["A", "B", "C"], ["a", "b", "c"], ["A", "C", "A"]));
const duplicateAssetTelemetry = await multiTelemetry(circularParticipants(["A", "B", "C"], ["a", "a", "c"]));
const duplicateFranchiseTelemetry = await multiTelemetry(circularParticipants(["A", "A", "C"]));
const ownershipAssets = [{ ...asset("a", 1000), ownerId: "B" }, { ...asset("b", 1000), ownerId: "B" }, { ...asset("c", 1000), ownerId: "C" }];
const ownershipRuntime = { ...runtime, catalog: { ...runtime.catalog, assets: ownershipAssets, byAssetId: Object.fromEntries(ownershipAssets.map((item) => [item.assetId, item])) } };
const ownershipTelemetry = await multiTelemetry(circularParticipants(["A", "B", "C"]), createTradeAnalyzerPostHandler({ ...enabled, loadRuntime: async () => ownershipRuntime }));
console.info = originalConsoleInfo;
const telemetrySafe = [emptyTelemetry, invalidDestinationTelemetry, selfDestinationTelemetry, duplicateAssetTelemetry, duplicateFranchiseTelemetry, ownershipTelemetry].every((line) => !line.includes("assetId\":\"a\"") && !line.includes("Player") && !line.includes("5000") && !line.includes("@example"));
check("telemetry_empty_package", emptyTelemetry.includes('"validationErrorCode":"EMPTY_OUTGOING_PACKAGE"'), "empty outgoing package emits a safe code");
check("telemetry_invalid_destination", invalidDestinationTelemetry.includes('"validationErrorCode":"INVALID_DESTINATION"'), "invalid destination emits a safe code");
check("telemetry_self_destination", selfDestinationTelemetry.includes('"validationErrorCode":"SELF_DESTINATION"'), "self destination emits a safe code");
check("telemetry_duplicate_asset", duplicateAssetTelemetry.includes('"validationErrorCode":"DUPLICATE_ASSET"'), "duplicate asset emits a safe code");
check("telemetry_duplicate_franchise", duplicateFranchiseTelemetry.includes('"validationErrorCode":"DUPLICATE_FRANCHISE"'), "duplicate franchise emits a safe code");
check("telemetry_ownership", ownershipTelemetry.includes('"validationErrorCode":"ASSET_NOT_OWNED"') && ownershipTelemetry.includes('"ownershipValidationResult":"FAIL"'), "ownership failure emits a safe code");
check("telemetry_redaction", telemetrySafe, "telemetry contains structural metadata only");
const limited = new BestEffortRateLimiter();
const limitedHandler = createTradeAnalyzerPostHandler({ ...enabled, limiter: limited });
let lastRateResponse: Response | null = null;
for (let index = 0; index < 36; index += 1) lastRateResponse = await responseOf(limitedHandler, json());
check("rate_limit", lastRateResponse?.status === 429, "rate policy enforced");
check("unexpected_failure", (await responseOf(createTradeAnalyzerPostHandler({ ...enabled, loadRuntime: async () => { throw new Error("filesystem path secret"); } }), json())).status === 503, "runtime failure becomes safe snapshot-unavailable response");
const internalText = privateBody;
check("redaction", !internalText.includes("winner") && !internalText.includes("tradeAdvice"), "no winner/advice fields");
const parityCases = [["a", "b"], ["a", "c"], ["b", "d"], ["c", "e"], ["d", "f"], ["a", "b"], ["b", "c"], ["c", "d"], ["d", "e"], ["e", "f"]];
const parity = await Promise.all(parityCases.map(async ([a, b]) => { const response = await responseOf(createTradeAnalyzerPostHandler({ ...enabled, limiter: new BestEffortRateLimiter() }), json([a], [b])); const body = JSON.parse(await response.text()); const direct = analyzeTradeInternal({ sideA: { assetIds: [a] }, sideB: { assetIds: [b] }, evaluatedAt: "2026-08-26T12:00:00.000Z", leaguePhase: "DRAFT_WINDOW", outputMode: "INTERNAL" }, { catalog, snapshot: runtime.snapshot, modelVersions: { valuationPolicyVersion: "valuation-v1", fairnessModelVersion: "fairness-v1" } }); return response.status === 200 && body.data.trade.fairnessScore?.internal === direct.trade?.fairnessScore?.internal && body.data.trade.fairnessBand === direct.trade?.fairnessBand; }));
check("service_api_parity", parity.every(Boolean), "10 gated route results match service/engine results");
const failures = checks.filter((item) => !item.pass);
console.log(JSON.stringify({ status: failures.length ? "FAIL" : "PASS", checks, noProductionGatesEnabled: true, noWrites: true, noTradeExecution: true, failures }, null, 2));
if (failures.length) process.exitCode = 1;
