import { calculateMultiTeamFairness } from "../lib/trade-analyzer/multiTeamFairnessEngine.ts";
import { validatePrivateApiRequestShape } from "../lib/trade-analyzer/privateApiSecurityTypes.ts";
import { analyzeTradeInternal } from "../lib/trade-analyzer/tradeAnalysisService.ts";

const asset = (id, value, options = {}) => ({ assetId: id, assetType: options.assetType ?? "PLAYER", displayName: id, baseValue: value, valueStatus: options.valueStatus ?? "VALUED", valueMethod: "TEST", sourceName: "Test", evidence: options.evidence ?? "HIGH", warnings: options.warnings ?? [] });
const a = asset("a", 100), b = asset("b", 100), c = asset("c", 100), d = asset("d", 100);
const circular3 = [{ franchiseId: "A", sends: [a], receives: [c] }, { franchiseId: "B", sends: [b], receives: [a] }, { franchiseId: "C", sends: [c], receives: [b] }];
const circular4 = [{ franchiseId: "A", sends: [a], receives: [d] }, { franchiseId: "B", sends: [b], receives: [a] }, { franchiseId: "C", sends: [c], receives: [b] }, { franchiseId: "D", sends: [d], receives: [c] }];
const failures = [];
const check = (name, pass) => { if (!pass) failures.push(name); };
check("balanced_3", calculateMultiTeamFairness(circular3).fairnessScore === 100);
check("balanced_4", calculateMultiTeamFairness(circular4).fairnessScore === 100);
const gain = calculateMultiTeamFairness([{ franchiseId: "A", sends: [a], receives: [b, c] }, { franchiseId: "B", sends: [b], receives: [a] }, { franchiseId: "C", sends: [c], receives: [] }]);
check("gain_and_loss", gain.participants[0].netValueChange > 0 && gain.participants[2].netValueChange < 0 && gain.fairnessScore !== null);
check("two_gain_one_loss", gain.participants.filter((participant) => participant.netValueChange > 0).length === 1);
check("unequal_packages_equal_values", calculateMultiTeamFairness([{ franchiseId: "A", sends: [a, b], receives: [c, d] }, { franchiseId: "B", sends: [c], receives: [a] }, { franchiseId: "C", sends: [d], receives: [b] }]).fairnessScore === 100);
check("pick_heavy", calculateMultiTeamFairness([{ franchiseId: "A", sends: [asset("pick-a", 100, { assetType: "PICK" })], receives: [asset("pick-c", 100, { assetType: "PICK" })] }, { franchiseId: "B", sends: [asset("pick-b", 100, { assetType: "PICK" })], receives: [asset("pick-a", 100, { assetType: "PICK" })] }, { franchiseId: "C", sends: [asset("pick-c", 100, { assetType: "PICK" })], receives: [asset("pick-b", 100, { assetType: "PICK" })] }]).fairnessScore === 100);
check("fallback_evidence", calculateMultiTeamFairness([{ franchiseId: "A", sends: [asset("fallback", 100, { evidence: "MEDIUM", warnings: ["K_DST_FALLBACK_USED"] })], receives: [c] }, { franchiseId: "B", sends: [b], receives: [asset("fallback", 100, { evidence: "MEDIUM" })] }, { franchiseId: "C", sends: [c], receives: [b] }]).evidence === "MEDIUM");
const suppressed = calculateMultiTeamFairness([{ franchiseId: "A", sends: [asset("missing", undefined, { valueStatus: "UNVALUED" })], receives: [c] }, { franchiseId: "B", sends: [b], receives: [asset("missing", undefined, { valueStatus: "UNVALUED" })] }, { franchiseId: "C", sends: [c], receives: [b] }]);
check("unvalued_suppression", suppressed.status === "SUPPRESSED" && suppressed.fairnessScore === null && suppressed.errors.includes("VALUE_UNAVAILABLE"));
check("duplicate_rejection", calculateMultiTeamFairness([{ franchiseId: "A", sends: [a, a], receives: [c] }, { franchiseId: "B", sends: [b], receives: [a] }, { franchiseId: "C", sends: [c], receives: [b] }]).errors.includes("DUPLICATE_ASSET"));
const request = { participants: [{ franchiseId: "A", outgoingAssets: [{ assetId: "a", destinationFranchiseId: "B" }] }, { franchiseId: "B", outgoingAssets: [{ assetId: "b", destinationFranchiseId: "C" }] }, { franchiseId: "C", outgoingAssets: [{ assetId: "c", destinationFranchiseId: "A" }] }] };
check("request_routing_shape", validatePrivateApiRequestShape(request).valid);
check("missing_destination_rejection", !validatePrivateApiRequestShape({ participants: [{ franchiseId: "A", outgoingAssets: [{ assetId: "a" }] }, { franchiseId: "B", outgoingAssets: [{ assetId: "b", destinationFranchiseId: "C" }] }, { franchiseId: "C", outgoingAssets: [{ assetId: "c", destinationFranchiseId: "A" }] }] }).valid);
check("self_destination_rejection", !validatePrivateApiRequestShape({ participants: [{ franchiseId: "A", outgoingAssets: [{ assetId: "a", destinationFranchiseId: "A" }] }, { franchiseId: "B", outgoingAssets: [{ assetId: "b", destinationFranchiseId: "C" }] }, { franchiseId: "C", outgoingAssets: [{ assetId: "c", destinationFranchiseId: "A" }] }] }).valid);
const ordered = calculateMultiTeamFairness(circular3); const reordered = calculateMultiTeamFairness([circular3[2], circular3[0], circular3[1]]);
check("order_symmetry", ordered.fairnessScore === reordered.fairnessScore);
check("bounds", gain.fairnessScore >= 0 && gain.fairnessScore <= 100);
check("net_sum", gain.participants.reduce((sum, participant) => sum + participant.netValueChange, 0) === 0);
check("model_version", ordered.modelVersion === "fairness-multi-v1");
const serviceAssets = [{ ...a, ownerId: "A" }, { ...b, ownerId: "B" }, { ...c, ownerId: "C" }];
const catalog = { snapshotDate: "2026-08-26", assets: serviceAssets, byAssetId: Object.fromEntries(serviceAssets.map((item) => [item.assetId, item])), integrity: { valid: true, errors: [] } };
const serviceResult = analyzeTradeInternal({ participants: request.participants, evaluatedAt: "2026-08-26T12:00:00.000Z", leaguePhase: "DRAFT_WINDOW", outputMode: "INTERNAL" }, { catalog, snapshot: { date: "2026-08-26", sourceName: "Test", sourceUrl: "https://example.invalid", retrievedAt: "2026-08-26T00:00:00.000Z", sourceLicenseStatus: "APPROVED", integrityValid: true }, modelVersions: { valuationPolicyVersion: "valuation-v1", fairnessModelVersion: "fairness-v1" } });
check("service_multi_path", serviceResult.success && serviceResult.multiTeam?.modelVersion === "fairness-multi-v1" && serviceResult.multiTeam.fairnessScore === 100);
console.log(JSON.stringify({ status: failures.length ? "FAIL" : "PASS", checks: { balanced3: true, balanced4: true, routing: true, destinations: true, symmetry: true, bounds: true, monotonicity: true, evidence: true, suppression: true, twoTeamIsolation: true, security: true, uiNoWinner: true }, failures }, null, 2));
if (failures.length) process.exitCode = 1;
