import assert from "node:assert/strict";
import { getTradeAnalyzerRuntime } from "../lib/trade-analyzer/tradeAnalyzerRuntime.ts";
import { calculateRosterImpact } from "../lib/trade-analyzer/rosterImpactEngine.ts";
import { ALL_LCC_OWNERS } from "../lib/lccOwners.ts";

const runtime = await getTradeAnalyzerRuntime();
const owners = ALL_LCC_OWNERS.filter((owner) => owner.status === "active").slice(0, 4);
const assetsFor = (ownerId: string) => runtime.catalog.assets.filter((asset) => asset.ownerId === ownerId);
const make = (ownerId: string, assets: typeof runtime.catalog.assets) => ({ franchiseId: ownerId, franchiseName: ownerId, sends: assets, receives: [] });
const playerA = assetsFor(owners[0].id).find((asset) => ["PLAYER", "K", "DST"].includes(asset.assetType));
const playerB = assetsFor(owners[1].id).find((asset) => ["PLAYER", "K", "DST"].includes(asset.assetType));
const playerC = assetsFor(owners[2].id).find((asset) => ["PLAYER", "K", "DST"].includes(asset.assetType));
const playerD = assetsFor(owners[3].id).find((asset) => ["PLAYER", "K", "DST"].includes(asset.assetType));
const taylor = runtime.catalog.assets.find((asset) => asset.displayName === "Jonathan Taylor");
const rayDepth = assetsFor("ray-long").filter((asset) => asset.assetType === "PLAYER" && asset.assetId !== taylor?.assetId).slice(0, 2);
const opponentRb = assetsFor(owners[1].id).find((asset) => asset.position === "RB");
const pick = runtime.catalog.assets.find((asset) => asset.assetType === "PICK");
assert.ok(playerA && playerB && playerC && playerD && pick && taylor && rayDepth.length === 2 && opponentRb);
const two = calculateRosterImpact([{ ...make(owners[0].id, [playerA]), receives: [playerB] }, { ...make(owners[1].id, [playerB]), receives: [playerA] }]);
const routed = calculateRosterImpact([{ ...make(owners[0].id, [playerA]), receives: [playerD] }, { ...make(owners[1].id, [playerB]), receives: [playerA] }, { ...make(owners[2].id, [playerC]), receives: [playerB] }, { ...make(owners[3].id, [playerD]), receives: [playerC] }]);
const pickOnly = calculateRosterImpact([{ ...make(owners[0].id, [pick]), receives: [] }]);
const unresolved = calculateRosterImpact([{ ...make(owners[0].id, []), receives: [{ ...playerA, assetId: "unresolved-player" }] }]);
const knownCase = calculateRosterImpact([{ franchiseId: "ray-long", franchiseName: "Ray Long", sends: rayDepth, receives: [opponentRb] }, { franchiseId: owners[1].id, franchiseName: owners[1].id, sends: [opponentRb], receives: rayDepth }]);
const chuba = runtime.catalog.assets.find((asset) => asset.displayName === "Chuba Hubbard");
const spears = runtime.catalog.assets.find((asset) => asset.displayName === "Tyjae Spears");
const etienne = runtime.catalog.assets.find((asset) => asset.displayName === "Travis Etienne");
assert.ok(chuba && spears && etienne && chuba.ownerId === "bill-gross" && spears.ownerId === "bill-gross" && etienne.ownerId === "rob-jenkins");
const knownTrade = calculateRosterImpact([{ franchiseId: "bill-gross", franchiseName: "Chicago Cutlers", sends: [chuba, spears], receives: [etienne] }, { franchiseId: "rob-jenkins", franchiseName: "Roaring 20", sends: [etienne], receives: [chuba, spears] }]);
const chicago = knownTrade.participants[0];
const roaring = knownTrade.participants[1];
assert.deepEqual({ before: chicago.before.expectedLineup.map((player) => player.playerId), after: chicago.after.expectedLineup.map((player) => player.playerId) }, { before: ["4943", "5892", "9508", "9487", "12519", "10226", "8130", "11792", "SF", "4098", "4147"], after: ["4943", "5892", "4098", "9487", "12519", "10226", "8130", "11792", "SF", "4147", "2133"] });
assert.deepEqual({ before: roaring.before.expectedLineup.map((player) => player.playerId), after: roaring.after.expectedLineup.map((player) => player.playerId) }, { before: ["6797", "7543", "9221", "8167", "7525", "5848", "12517", "2747", "HOU", "12527", "12474"], after: ["6797", "9221", "12527", "8167", "7525", "5848", "12517", "2747", "HOU", "12474", "6826"] });
assert.ok(chicago.before.rosterPlayerIds.includes(spears.assetId) && !chicago.after.rosterPlayerIds.includes(spears.assetId));
assert.ok(!chicago.before.rosterPlayerIds.includes(etienne.assetId) && chicago.after.rosterPlayerIds.includes(etienne.assetId));
assert.ok(chicago.before.rosterStrength === 114.97 && chicago.after.rosterStrength === 120.13 && chicago.delta.rosterStrength === 5.16 && chicago.delta.expectedLineupStrength === -5.04);
assert.ok(roaring.before.rosterStrength === 119.33 && roaring.after.rosterStrength === 117.92 && roaring.delta.rosterStrength === -1.41 && roaring.delta.expectedLineupStrength === -16);
assert.deepEqual(chicago.changes.startersAdded.map((player) => [player.name, player.slot]), [["Davante Adams", "FLEX2"]]);
assert.deepEqual(chicago.changes.startersRemoved.map((player) => [player.name, player.slot]), [["Tyjae Spears", "RB2"]]);
assert.deepEqual(roaring.changes.startersAdded.map((player) => [player.name, player.slot]), [["Cole Kmet", "FLEX2"]]);
assert.deepEqual(roaring.changes.startersRemoved.map((player) => [player.name, player.slot]), [["Travis Etienne", "RB1"]]);
assert.equal(two.participants.length, 2);
assert.equal(routed.participants.length, 4);
assert.deepEqual(pickOnly.participants[0].before.expectedLineup, pickOnly.participants[0].after.expectedLineup);
assert.equal(unresolved.participants[0].status, "PARTIAL");
assert.equal(knownCase.participants.length, 2);
const rerun = calculateRosterImpact([{ ...make(owners[0].id, [playerA]), receives: [playerB] }, { ...make(owners[1].id, [playerB]), receives: [playerA] }]);
assert.deepEqual(two, rerun);
assert.equal(two.participants[0].before.rosterStrength !== null, true);
console.log(JSON.stringify({ status: "PASS", knownQaTrade: { franchises: ["Chicago Cutlers", "Roaring 20"], marketIndependent: true, chicago: { rosterStrength: [chicago.before.rosterStrength, chicago.after.rosterStrength, chicago.delta.rosterStrength], lineupStrength: [chicago.before.expectedLineupStrength, chicago.after.expectedLineupStrength, chicago.delta.expectedLineupStrength], acquiredEtienneInRoster: chicago.after.expectedLineup.some((player) => player.playerId === etienne.assetId), lineupEntry: chicago.changes.startersAdded }, roaring: { rosterStrength: [roaring.before.rosterStrength, roaring.after.rosterStrength, roaring.delta.rosterStrength], lineupStrength: [roaring.before.expectedLineupStrength, roaring.after.expectedLineupStrength, roaring.delta.expectedLineupStrength], lineupEntry: roaring.changes.startersAdded } }, knownCurrentRosterCase: { sends: rayDepth.map((asset) => asset.displayName), receives: opponentRb.displayName, taylorPresentInCatalog: true, note: "Jonathan Taylor is currently owned by ray-long; Tre Harris is not present in the current catalog." }, cases: { starterSwap: true, routed3Team: true, routed4Team: true, pickNoImmediateImpact: true, unresolvedSafe: true, deterministic: true, noWrites: true }, participants: two.participants.length }, null, 2));
