import { createTradeAnalyzerPostHandler } from "../app/api/trade-analyzer/analyze/route.ts";
import { BestEffortRateLimiter } from "../lib/trade-analyzer/tradeAnalyzerRouteSupport.ts";
import { requestOriginAllowed } from "../lib/trade-analyzer/tradeAnalyzerRouteSupport.ts";
import { analyzeTradeInternal } from "../lib/trade-analyzer/tradeAnalysisService.ts";
import type { CurrentAssetCatalog, CurrentCatalogAsset } from "../lib/trade-analyzer/types.ts";
import type { LccMemberSession } from "../lib/auth/types.ts";

const checks: { name: string; pass: boolean; detail: string }[] = [];
const check = (name: string, pass: boolean, detail: string) => checks.push({ name, pass, detail });
process.env.NEXT_PUBLIC_APP_URL ??= "https://long-country-club-ffl.web.app";
const asset = (id: string, value: number): CurrentCatalogAsset => ({ assetId: id, assetType: "PLAYER", displayName: id, position: "WR", baseValue: value, valueStatus: "VALUED", valueMethod: "FANTASYCALC_DIRECT", sourceName: "FantasyCalc", sourceRowId: id, snapshotDate: "2026-08-26", evidence: "HIGH", ownerId: "active-owner" });
const assets = [asset("a", 5000), asset("b", 4500), asset("c", 3000), asset("d", 2500), asset("e", 1500), asset("f", 1000)];
const catalog: CurrentAssetCatalog = { snapshotDate: "2026-08-26", assets, byAssetId: Object.fromEntries(assets.map((item) => [item.assetId, item])), integrity: { valid: true, errors: [] } };
const runtime = { catalog, snapshot: { date: "2026-08-26", sourceName: "FantasyCalc", sourceUrl: "https://example.invalid/source", retrievedAt: "2026-08-26T00:00:00.000Z", sourceLicenseStatus: "APPROVED", integrityValid: true } };
const member = (ownerId = "active-owner"): LccMemberSession => ({ identity: { uid: `${ownerId}-uid`, email: `${ownerId}@example.invalid`, name: ownerId, picture: null }, member: { memberId: ownerId, ownerId, displayName: ownerId, teamName: "Test Team", capabilities: [] } });
const unauthenticated = (): Promise<LccMemberSession | null> => Promise.resolve(null);
const enabled = { featureEnabled: () => true, licenseApproved: () => true, loadRuntime: async () => runtime, getSession: async () => member(), now: () => new Date("2026-08-26T12:00:00.000Z") };
const request = (body: string, init: RequestInit = {}) => new Request("http://localhost/api/trade-analyzer/analyze", { method: "POST", headers: { "content-type": "application/json", origin: "https://long-country-club-ffl.web.app" }, body, ...init });
const json = (sideA = ["a"], sideB = ["b"], extra: Record<string, unknown> = {}) => JSON.stringify({ sideA: { assetIds: sideA }, sideB: { assetIds: sideB }, ...extra });
const bodyOf = async (response: Response) => response.text();
const responseOf = async (handler: ReturnType<typeof createTradeAnalyzerPostHandler>, body: string, init?: RequestInit) => handler(request(body, init));

const featureOff = await responseOf(createTradeAnalyzerPostHandler({ getSession: async () => member(), featureEnabled: () => false, licenseApproved: () => true, loadRuntime: async () => runtime }), json());
const licenseOff = await responseOf(createTradeAnalyzerPostHandler({ ...enabled, licenseApproved: () => false }), json());
const privateOn = await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a"], ["b"], { validateOwnership: true }));
check("feature_off", featureOff.status === 403 && !(await bodyOf(featureOff)).includes("5000"), "FEATURE_NOT_AVAILABLE blocks without values");
check("license_off", licenseOff.status === 403 && !(await bodyOf(licenseOff)).includes("5000"), "SOURCE_LICENSE_UNAPPROVED blocks without values");
const privateBody = await bodyOf(privateOn);
check("private_on", privateOn.status === 200 && privateBody.includes('"ok":true') && privateBody.includes('"fairnessScore"'), "enabled local active-member request returns analysis");
const multiAssets = ["A", "B", "C", "D"].map((owner, index) => ({ ...asset(String.fromCharCode(97 + index), 1000), ownerId: owner }));
const multiRuntime = { ...runtime, catalog: { ...runtime.catalog, assets: multiAssets, byAssetId: Object.fromEntries(multiAssets.map((item) => [item.assetId, item])) } };
const multiHandler = createTradeAnalyzerPostHandler({ ...enabled, loadRuntime: async () => multiRuntime });
const multiPayload = (participants: string[], sandbox?: boolean) => ({ participants: participants.map((franchiseId, index) => ({ franchiseId, outgoingAssets: [{ assetId: String.fromCharCode(97 + index), destinationFranchiseId: participants[(index + 1) % participants.length] }] })), ...(sandbox === undefined ? {} : { sandbox }) });
const league3 = await responseOf(multiHandler, JSON.stringify(multiPayload(["A", "B", "C"])));
const league4 = await responseOf(multiHandler, JSON.stringify(multiPayload(["A", "B", "C", "D"])));
const sandbox2 = await responseOf(createTradeAnalyzerPostHandler({ ...enabled, loadRuntime: async () => multiRuntime }), json(["a"], ["b"], { sandbox: true }));
const sandbox3 = await responseOf(createTradeAnalyzerPostHandler({ ...enabled, loadRuntime: async () => multiRuntime }), JSON.stringify(multiPayload(["Team A", "Team B", "Team C"], true)));
const sandbox4 = await responseOf(createTradeAnalyzerPostHandler({ ...enabled, loadRuntime: async () => multiRuntime }), JSON.stringify(multiPayload(["Team A", "Team B", "Team C", "Team D"], true)));
const leagueWithFalseSandbox = analyzeTradeInternal({ ...multiPayload(["A", "B", "C"]), evaluatedAt: "2026-08-26T12:00:00.000Z", leaguePhase: "DRAFT_WINDOW", outputMode: "INTERNAL", sandbox: false }, { catalog: multiRuntime.catalog, snapshot: runtime.snapshot, modelVersions: { valuationPolicyVersion: "valuation-v1", fairnessModelVersion: "fairness-v1" } });
check("league_multi_3_route", league3.status === 200 && (await bodyOf(league3)).includes('"multiTeam"'), "UI-shaped 3-team League request reaches fairness-multi-v1");
check("league_multi_4_route", league4.status === 200 && (await bodyOf(league4)).includes('"multiTeam"'), "UI-shaped 4-team League request reaches fairness-multi-v1");
check("sandbox_two_team", sandbox2.status === 200, "2-team Sandbox request remains valid");
check("sandbox_multi_3_route", sandbox3.status === 200 && (await bodyOf(sandbox3)).includes('"multiTeam"'), "3-team Sandbox forwards sandbox true");
check("sandbox_multi_4_route", sandbox4.status === 200 && (await bodyOf(sandbox4)).includes('"multiTeam"'), "4-team Sandbox forwards sandbox true");
check("sandbox_false_service_contract", leagueWithFalseSandbox.status === "INVALID_REQUEST", "League multi-team sandbox false remains invalid at the service boundary");
const rosterImpactUnavailable = await responseOf(createTradeAnalyzerPostHandler(enabled), JSON.stringify({ sideA: { assetIds: ["a"], ownerId: "current-roster-unavailable" }, sideB: { assetIds: ["b"], ownerId: "current-roster-unavailable-b" }, validateOwnership: false }));
const rosterImpactUnavailableBody = JSON.parse(await bodyOf(rosterImpactUnavailable));
check("roster_impact_non_blocking", rosterImpactUnavailable.status === 200 && rosterImpactUnavailableBody.ok === true && rosterImpactUnavailableBody.data.rosterImpact?.participants.every((participant: { status: string }) => participant.status === "INCOMPLETE"), "valid market analysis remains available when roster impact is incomplete");
check("auth_matrix", (await responseOf(createTradeAnalyzerPostHandler({ ...enabled, getSession: unauthenticated }), json())).status === 401 && (await responseOf(createTradeAnalyzerPostHandler({ ...enabled, getSession: async () => ({ ...member(), member: null }) }), json())).status === 403 && (await responseOf(createTradeAnalyzerPostHandler({ ...enabled, getSession: async () => member("commissioner") }), json())).status === 200, "unauthenticated/unknown/retired deny; active and commissioner allow");
check("method", (await createTradeAnalyzerPostHandler(enabled)(new Request("http://localhost/api/trade-analyzer/analyze", { method: "GET" }))).status === 405, "GET cannot calculate");
check("content_type", (await responseOf(createTradeAnalyzerPostHandler(enabled), json(), { headers: { "content-type": "text/plain", origin: "https://long-country-club-ffl.web.app" } })).status === 415 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(), { headers: { "content-type": "application/json; charset=utf-8", origin: "https://long-country-club-ffl.web.app" } })).status === 200, "JSON required; charset accepted");
check("body_limit", (await responseOf(createTradeAnalyzerPostHandler(enabled), "x".repeat(16 * 1024 + 1))).status === 413, "16 KB body limit");
check("malformed_json", (await responseOf(createTradeAnalyzerPostHandler(enabled), "{bad")).status === 400, "malformed JSON returns 400");
check("schema_limits", (await responseOf(createTradeAnalyzerPostHandler(enabled), json([], ["b"]))).status === 400 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(Array.from({ length: 16 }, (_, index) => String(index)), ["b"]))).status === 400 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a"], ["b"], { ownerId: "spoofed" }))).status === 400, "empty, oversized, and unexpected fields rejected");
check("spoofing", (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a"], ["b"], { baseValue: 999999, snapshot: "fake", modelVersion: "fake" }))).status === 400, "client value/snapshot/model spoofing rejected");
check("duplicates", (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a", "a"], ["b"]))).status === 400 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["a"], ["a"]))).status === 400 && (await responseOf(createTradeAnalyzerPostHandler(enabled), json(["unknown"], ["b"]))).status === 400, "duplicate and unknown assets rejected");
const unknownResponse = await responseOf(createTradeAnalyzerPostHandler(enabled), json(["unknown"], ["b"]));
const unknownBody = await bodyOf(unknownResponse);
check("safe_error_detail", unknownResponse.status === 400 && unknownBody.includes("selected assets are no longer available") && !unknownBody.includes("at /"), "deterministic validation errors map to safe owner-facing messages");
check("origin", (await responseOf(createTradeAnalyzerPostHandler(enabled), json(), { headers: { "content-type": "application/json", origin: "https://evil.example" } })).status === 403, "cross-origin request rejected");
const proxiedOriginRequest = new Request("https://ssrlongcountryclubffl-tfhicrqlta-uc.a.run.app/api/trade-analyzer/analyze", { method: "POST", headers: { "content-type": "application/json", origin: "https://long-country-club-ffl.web.app" }, body: json() });
check("firebase_proxy_origin", requestOriginAllowed(proxiedOriginRequest) && (await createTradeAnalyzerPostHandler(enabled)(proxiedOriginRequest)).status === 200, "canonical Hosting Origin is accepted when request.url is the internal SSR origin");
const missingOriginRequest = new Request("https://ssrlong-country-club-ffl-tfhicrqlta-uc.a.run.app/api/trade-analyzer/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: json() });
check("missing_origin", !requestOriginAllowed(missingOriginRequest), "missing Origin fails closed");
const previousConfiguredOrigin = process.env.NEXT_PUBLIC_APP_URL;
process.env.NEXT_PUBLIC_APP_URL = "https://wrong.example";
check("configured_origin_mismatch", !requestOriginAllowed(proxiedOriginRequest), "mismatched configured origin is rejected");
process.env.NEXT_PUBLIC_APP_URL = previousConfiguredOrigin;
const spoofedForwardedHostRequest = new Request("https://ssrlongcountryclubffl-tfhicrqlta-uc.a.run.app/api/trade-analyzer/analyze", { method: "POST", headers: { "content-type": "application/json", origin: "https://long-country-club-ffl.web.app", host: "evil.example", "x-forwarded-host": "evil.example", "x-forwarded-proto": "http" }, body: json() });
check("forwarded_host_not_authority", requestOriginAllowed(spoofedForwardedHostRequest), "Host and forwarded headers do not override configured Origin authority");
const limited = new BestEffortRateLimiter();
const limitedHandler = createTradeAnalyzerPostHandler({ ...enabled, limiter: limited });
let lastRateResponse: Response | null = null;
for (let index = 0; index < 36; index += 1) lastRateResponse = await responseOf(limitedHandler, json());
check("rate_limit", lastRateResponse?.status === 429, "rate policy enforced");
check("unexpected_failure", (await responseOf(createTradeAnalyzerPostHandler({ ...enabled, loadRuntime: async () => { throw new Error("filesystem path secret"); } }), json())).status === 503, "runtime failure becomes safe snapshot-unavailable response");
const internalText = privateBody;
check("redaction", !internalText.includes("winner") && !internalText.includes("tradeAdvice"), "no winner/advice fields");
const parityCases = [["a", "b"], ["a", "c"], ["b", "d"], ["c", "e"], ["d", "f"], ["a", "b"], ["b", "c"], ["c", "d"], ["d", "e"], ["e", "f"]];
const parity = await Promise.all(parityCases.map(async ([a, b]) => { const response = await responseOf(createTradeAnalyzerPostHandler({ ...enabled, limiter: new BestEffortRateLimiter() }), json([a], [b])); const body = JSON.parse(await response.text()); const direct = analyzeTradeInternal({ sideA: { assetIds: [a] }, sideB: { assetIds: [b] }, evaluatedAt: "2026-08-26T12:00:00.000Z", leaguePhase: "DRAFT_WINDOW", outputMode: "INTERNAL" }, { catalog, snapshot: runtime.snapshot, modelVersions: { valuationPolicyVersion: "valuation-v1", fairnessModelVersion: "fairness-v1" } }); return response.status === 200 && body.data.trade.fairnessScore?.internal === direct.trade?.fairnessScore?.internal && body.data.trade.fairnessBand === direct.trade?.fairnessBand; }));
check("service_api_parity", parity.every(Boolean), "10 gated route results match service/engine results");
const failures = checks.filter((item) => !item.pass);
console.log(JSON.stringify({ status: failures.length ? "FAIL" : "PASS", checks, noProductionGatesEnabled: true, noWrites: true, noTradeExecution: true, failures }, null, 2));
if (failures.length) process.exitCode = 1;
