import assert from "node:assert/strict";
import { getTradeAnalyzerRuntime } from "../lib/trade-analyzer/tradeAnalyzerRuntime.ts";
import { calculateRosterImpact } from "../lib/trade-analyzer/rosterImpactEngine.ts";
import { ALL_LCC_OWNERS } from "../lib/lccOwners.ts";

const runtime = await getTradeAnalyzerRuntime();
const owners = ALL_LCC_OWNERS.filter((owner) => owner.status === "active").slice(0, 4);
const assetsFor = (ownerId: string) => runtime.catalog.assets.filter((asset) => asset.ownerId === ownerId);
const make = (ownerId: string, assets: typeof runtime.catalog.assets) => ({ franchiseId: ownerId, franchiseName: ownerId, sends: assets, receives: [] });
const playerA = assetsFor(owners[0].id).find((asset) => ["PLAYER", "K", "DST"].includes(asset.assetType));
const playerB = assetsFor(owners[1].id).find((asset) => ["PLAYER", "K", "DST"].includes(asset.assetType));
const playerC = assetsFor(owners[2].id).find((asset) => ["PLAYER", "K", "DST"].includes(asset.assetType));
const playerD = assetsFor(owners[3].id).find((asset) => ["PLAYER", "K", "DST"].includes(asset.assetType));
const taylor = runtime.catalog.assets.find((asset) => asset.displayName === "Jonathan Taylor");
const rayDepth = assetsFor("ray-long").filter((asset) => asset.assetType === "PLAYER" && asset.assetId !== taylor?.assetId).slice(0, 2);
const opponentRb = assetsFor(owners[1].id).find((asset) => asset.position === "RB");
const pick = runtime.catalog.assets.find((asset) => asset.assetType === "PICK");
assert.ok(playerA && playerB && playerC && playerD && pick && taylor && rayDepth.length === 2 && opponentRb);
const two = calculateRosterImpact([{ ...make(owners[0].id, [playerA]), receives: [playerB] }, { ...make(owners[1].id, [playerB]), receives: [playerA] }]);
const routed = calculateRosterImpact([{ ...make(owners[0].id, [playerA]), receives: [playerD] }, { ...make(owners[1].id, [playerB]), receives: [playerA] }, { ...make(owners[2].id, [playerC]), receives: [playerB] }, { ...make(owners[3].id, [playerD]), receives: [playerC] }]);
const pickOnly = calculateRosterImpact([{ ...make(owners[0].id, [pick]), receives: [] }]);
const unresolved = calculateRosterImpact([{ ...make(owners[0].id, []), receives: [{ ...playerA, assetId: "unresolved-player" }] }]);
const knownCase = calculateRosterImpact([{ franchiseId: "ray-long", franchiseName: "Ray Long", sends: rayDepth, receives: [opponentRb] }, { franchiseId: owners[1].id, franchiseName: owners[1].id, sends: [opponentRb], receives: rayDepth }]);
assert.equal(two.participants.length, 2);
assert.equal(routed.participants.length, 4);
assert.deepEqual(pickOnly.participants[0].before.expectedLineup, pickOnly.participants[0].after.expectedLineup);
assert.equal(unresolved.participants[0].status, "PARTIAL");
assert.equal(knownCase.participants.length, 2);
const rerun = calculateRosterImpact([{ ...make(owners[0].id, [playerA]), receives: [playerB] }, { ...make(owners[1].id, [playerB]), receives: [playerA] }]);
assert.deepEqual(two, rerun);
assert.equal(two.participants[0].before.rosterStrength !== null, true);
console.log(JSON.stringify({ status: "PASS", knownCurrentRosterCase: { sends: rayDepth.map((asset) => asset.displayName), receives: opponentRb.displayName, taylorPresentInCatalog: true, note: "Jonathan Taylor is currently owned by ray-long; Tre Harris is not present in the current catalog." }, cases: { starterSwap: true, routed3Team: true, routed4Team: true, pickNoImmediateImpact: true, unresolvedSafe: true, deterministic: true, noWrites: true }, participants: two.participants.length }, null, 2));
