const halfUp = (value, digits = 0) => { const factor = 10 ** digits; return Math.floor(value * factor + 0.5) / factor; };
const band = (score) => score >= 97 && score <= 100 ? "VERY EVEN" : score >= 92 ? "FAIR" : score >= 82 ? "SLIGHT EDGE" : score >= 70 ? "CLEAR EDGE" : score >= 0 ? "LOPSIDED" : null;
const fairness = (a, b) => { if (![a, b].every((value) => Number.isFinite(value) && value >= 0) || a + b <= 0) return null; return Math.max(0, Math.min(100, 200 * Math.min(a, b) / (a + b))); };
const shares = (a, b) => { const total = a + b; if (!(total > 0)) return null; const first = halfUp(a / total * 100); return [first, 100 - first]; };
const statusFor = ({ unvalued = 0, unsupported = 0, invalid = false, freshness = "FRESH" }) => { if (invalid) return "INVALID"; if (unvalued || unsupported) return "SUPPRESSED"; return freshness === "FRESH" ? "AUTHORITATIVE" : "PROVISIONAL"; };
const evidenceFor = ({ unvalued = 0, unsupported = 0, fallback = 0, freshness = "FRESH" }) => { if (unvalued || unsupported) return "INCOMPLETE"; if (freshness === "STALE") return "LOW"; if (freshness === "AGING" || fallback) return "MEDIUM"; return "HIGH"; };
const vector = (name, a, b, options = {}) => { const score = fairness(a, b); const split = score === null ? null : shares(a, b); const status = statusFor(options); const evidence = evidenceFor(options); return { name, sideTotals: [a, b], marketSplit: split, fairness: status === "SUPPRESSED" || status === "INVALID" ? null : halfUp(score, 1), band: status === "SUPPRESSED" || status === "INVALID" ? null : band(score), resultStatus: status, evidence }; };
const vectors = [
  vector("A", 5000, 5000), vector("B", 5500, 4500), vector("C", 6000, 4000), vector("D", 6500, 3500), vector("E", 7000, 3000), vector("F", 9700, 300), vector("G", 10000, 0), vector("H", 25, 25, { fallback: 2 }), vector("I", 5025, 5025, { fallback: 1 }), vector("J", 5000, 5000, { unvalued: 1 }), vector("K", 5000, 5000, { unsupported: 1 }), vector("L", 0, 0, { invalid: true }), vector("M", 2776, 2776), vector("N", 3736, 2776), vector("O", 5000, 5000, { freshness: "FRESH" }), vector("P", 5000, 5000, { freshness: "AGING" }), vector("Q", 5000, 5000, { freshness: "STALE" }),
];
const boundaryTests = [{ score: 96.999, expected: "FAIR" }, { score: 97, expected: "VERY EVEN" }, { score: 91.999, expected: "SLIGHT EDGE" }, { score: 92, expected: "FAIR" }, { score: 81.999, expected: "CLEAR EDGE" }, { score: 82, expected: "SLIGHT EDGE" }, { score: 69.999, expected: "LOPSIDED" }, { score: 70, expected: "CLEAR EDGE" }].map((test) => ({ ...test, actual: band(test.score), pass: band(test.score) === test.expected }));
const symmetry = fairness(7000, 3000) === fairness(3000, 7000) && Math.abs((shares(7000, 3000)?.[0] ?? 0) - (100 - (shares(3000, 7000)?.[0] ?? 0))) < 1e-9;
const monotonicity = [1000, 2000, 3000, 4000, 5000].every((lower, index, values) => index === 0 || fairness(6000, lower) >= fairness(6000, values[index - 1]));
const invalidStates = { zeroCombined: fairness(0, 0) === null, negative: fairness(-1, 100) === null, nan: fairness(Number.NaN, 100) === null, infinity: fairness(Number.POSITIVE_INFINITY, 100) === null };
const result = { status: "PASS", formulas: { fairness: "200 * min(A,B) / (A+B)", shares: "A/(A+B), B/(A+B)", rounding: "decimal half-up" }, vectors, boundaryTests, properties: { symmetry, bounds: vectors.filter((v) => v.fairness !== null).every((v) => v.fairness >= 0 && v.fairness <= 100), monotonicity, equalTotal: fairness(5000, 5000) === 100, missingAsZeroPrevented: vectors.find((v) => v.name === "J")?.fairness === null, invalidStates }, evidenceAggregation: { fresh: evidenceFor({}), aging: evidenceFor({ freshness: "AGING" }), stale: evidenceFor({ freshness: "STALE" }), fallback: evidenceFor({ fallback: 1 }), unvalued: evidenceFor({ unvalued: 1 }), unsupported: evidenceFor({ unsupported: 1 }) }, freshnessStates: { fresh: statusFor({}), aging: statusFor({ freshness: "AGING" }), stale: statusFor({ freshness: "STALE" }) }, noRealTrades: true, noProductionEngine: true };
if (!result.boundaryTests.every((test) => test.pass) || !result.properties.symmetry || !result.properties.bounds || !result.properties.monotonicity || !result.properties.equalTotal || !Object.values(result.properties.invalidStates).every(Boolean)) { console.log(JSON.stringify({ ...result, status: "FAIL" }, null, 2)); process.exit(1); }
console.log(JSON.stringify(result, null, 2));
