import type { OperationalReconciliationResult, ReconciliationCheck } from '@/lib/finance/operationalReconciliation';

const money = (cents: number) => `$${(cents / 100).toFixed(2)}`;
const statusClass = (status: ReconciliationCheck['status']) => status === 'pass' ? 'lcc2-badge--info' : status === 'waiting' ? 'lcc2-badge--neutral' : status === 'action-required' ? 'lcc2-badge--warning' : 'lcc2-badge--warning';

export function ReconciliationChecks({ result }: { result: OperationalReconciliationResult }) {
  const summary = result.summary;
  return <section aria-labelledby="reconciliation-heading" className="mt-10 border-t border-[var(--lcc-color-border)] pt-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="lcc2-label text-[var(--lcc-brand-primary)]">Private read-only control</p><h2 id="reconciliation-heading" className="mt-2 font-ui text-2xl font-black text-[var(--lcc-color-text)]">Reconciliation Checks</h2><p className="lcc2-body mt-2">Derived operational checks only. Stored reconciliation status remains pending.</p></div><div className="rounded-xl border border-[var(--lcc-color-border)] bg-[var(--lcc-color-surface)] px-4 py-3"><p className="lcc2-label">Ready to close</p><p className="mt-1 font-ui text-xl font-black text-[var(--lcc-color-text)]">{result.readyToClose ? 'Yes' : 'No'}</p></div></div><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{result.checks.filter((item) => ['dues', 'awards', 'settlements', 'expenses', 'reserve', 'audit'].includes(item.key)).map((item) => <CheckRow key={item.key} item={item} />)}</div><div className="mt-5 rounded-xl border border-[var(--lcc-color-border)] bg-[var(--lcc-color-surface)] p-4"><p className="lcc2-label">Close blockers and preparation</p><div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2"><p className="lcc2-body">Dues outstanding: <strong>{money(summary.duesOutstandingCents)}</strong></p><p className="lcc2-body">Weekly waiting: <strong>{summary.weeklyWaitingCount}</strong></p><p className="lcc2-body">Postseason unresolved: <strong>{summary.postseasonWaitingCount}</strong></p><p className="lcc2-body">Approved unpaid: <strong>{summary.approvedUnpaidCount} · {money(summary.approvedUnpaidAmountCents)}</strong></p><p className="lcc2-body">Settlement records: <strong>{summary.settlementCount}</strong></p><p className="lcc2-body">Expected award slots: <strong>{summary.expectedAwardSlots}</strong></p></div>{result.blockingIssues.length ? <div className="mt-3 border-t border-[var(--lcc-color-border)] pt-3"><p className="lcc2-label">Blocking issues</p>{result.blockingIssues.map((issue) => <p key={issue} className="lcc2-body mt-1">{issue}</p>)}</div> : null}</div></section>;
}

function CheckRow({ item }: { item: ReconciliationCheck }) { return <article className="lcc2-card p-4"><div className="flex items-start justify-between gap-3"><p className="font-ui font-black text-[var(--lcc-color-text)]">{item.label}</p><span className={`lcc2-badge ${statusClass(item.status)}`}>{item.status}</span></div><p className="lcc2-body mt-2">{item.reason}</p><p className="lcc2-body mt-1 text-xs">{item.detail}</p></article>; }
