import type { SeasonCloseReadiness } from '@/lib/finance/seasonClose';

const money = (cents: number) => `$${(cents / 100).toFixed(2)}`;

export function SeasonCloseReadiness({ readiness }: { readiness: SeasonCloseReadiness }) {
  const preview = readiness.snapshotPreview;
  return <section aria-labelledby="season-close-heading" className="mt-10 border-t border-[var(--lcc-color-border)] pt-8"><div className="max-w-3xl"><p className="lcc2-label text-[var(--lcc-brand-primary)]">Finance Phase Two · Read-only</p><h2 id="season-close-heading" className="mt-2 font-ui text-2xl font-black text-[var(--lcc-color-text)]">Season Close</h2><p className="lcc2-body mt-2">Readiness and year-end snapshot preview only. The 2026 season remains active and no archive is created.</p></div><div className="mt-5 rounded-xl border border-[var(--lcc-semantic-warning)] bg-[var(--lcc-color-surface)] p-4"><p className="lcc2-label">Status</p><p className="mt-1 font-ui text-xl font-black text-[var(--lcc-color-text)]">{readiness.readyToClose ? 'READY TO CLOSE' : 'NOT READY TO CLOSE'}</p><p className="lcc2-body mt-1">Reconciliation: {readiness.reconciliationStatus}</p></div><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">{readiness.blockingChecks.map((blocker) => <div key={blocker} className="lcc2-card p-4"><p className="lcc2-body">{blocker}</p></div>)}</div><div className="mt-6 lcc2-card p-4 sm:p-5"><p className="lcc2-label">Year-End Snapshot Preview</p><p className="lcc2-body mt-1">PREVIEW ONLY · NOT CLOSED · NOT AUTHORITATIVE HISTORICAL ARCHIVE</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Dues assessed" value={money(preview.assessmentSummary.assessedCents)} /><Metric label="Dues collected" value={money(preview.assessmentSummary.collectedCents)} /><Metric label="Dues outstanding" value={money(preview.assessmentSummary.outstandingCents)} /><Metric label="Verified expenses" value={money(preview.expenseSummary.netCents)} /><Metric label="Approved awards" value={money(preview.totals.approvedAwardCents)} /><Metric label="Paid awards" value={money(preview.totals.paidAwardCents)} /><Metric label="VACU reserve" value={money(preview.restrictedReserve.amountCents)} /><Metric label="Champion projection" value={money(preview.championshipAllocation.projectedChampionCents)} /></div></div><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" disabled className="lcc2-button lcc2-button--primary disabled:cursor-not-allowed disabled:opacity-50">Close &amp; Archive Season</button><p className="lcc2-body">Archive target: {readiness.archiveTarget.firestore}</p></div></section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><p className="lcc2-label">{label}</p><p className="mt-1 font-ui text-base font-black text-[var(--lcc-color-text)]">{value}</p></div>; }
